/* Pure editor helpers. No execution or generated program output lives here. */
(function(root){'use strict';
const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function pattern(query,{regex=false,caseSensitive=false,wholeWord=false}={}){if(!query)return null;if(query.length>256)throw Error('Search pattern exceeds 256 characters.');if(regex&&(/\\[1-9]|\([^)]*[+*][^)]*\)[+*{]|\([^)]*\|[^)]*\)[+*{]/.test(query)))throw Error('This pattern could block the editor. Use a simpler expression.');let source=regex?query:escape(query);if(wholeWord)source='\\b(?:'+source+')\\b';return new RegExp(source,'g'+(caseSensitive?'':'i'));}
function matches(text,query,options={}){const re=pattern(query,options);if(!re)return [];const results=[];let m;while((m=re.exec(text))&&results.length<10000){results.push({from:m.index,to:m.index+m[0].length,text:m[0]});if(!m[0].length)re.lastIndex++;}return results;}
function replace(text,query,replacement,options={}){const re=pattern(query,options);return re?text.replace(re,options.regex?replacement:()=>replacement):text;}
function diagnostics(text){const results=[];for(const line of String(text).split('\n')){const m=line.match(/^\s*(.+?):(\d+):(\d+):\s*(?:fatal )?(error|warning|note):\s*(.*)/);if(m)results.push({file:m[1].replace(/^\/project\//,''),line:Number(m[2]),column:Number(m[3]),severity:m[4],raw:m[5]});}if(!results.length){const m=String(text).match(/File "([^"]+)", line (\d+)/g);if(m){const file=m.at(-1).match(/File "([^"]+)", line (\d+)/),lines=String(text).split('\n'),reason=lines.filter(x=>/\w+(?:Error|Exception):/.test(x)).at(-1)||lines.at(-1);results.push({file:file[1].replace(/^\/project\//,''),line:Number(file[2]),column:1,severity:'error',raw:reason});}}return results.slice(0,200);}
function format(text,language,indent=4,useTabs=false){if(language!=='py'&&(/\bR"/.test(text)||/\\\n/.test(text)))return text;const unit=useTabs?'\t':' '.repeat(indent);let depth=0,block=false,quote='',triple='',continuation=false;const result=[];for(const original of text.split('\n')){if(language==='py'){if(triple){result.push(original);if(original.includes(triple))triple='';continue;}const marker=original.match(/(?:^|[^\\])("""|''')/);if(marker&&original.split(marker[1]).length%2===0){triple=marker[1];result.push(original);continue;}result.push(original.trimEnd());continue;}if(continuation||/^\s*#/.test(original)||original.endsWith('\\')){continuation=original.endsWith('\\');result.push(original);continue;}const preserve=!!quote;const line=original.trim();let opens=0,closes=0,leadingClose=0,hasCode=false;for(let i=0;i<line.length;i++){const c=line[i],n=line[i+1];if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(quote){if(c==='\\'){i++;continue;}if(c===quote)quote='';continue;}if(c==='/'&&n==='/')break;if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"){quote=c;hasCode=true;continue;}if(c==='{')opens++;if(c==='}'){closes++;if(!hasCode)leadingClose++;}if(!/\s|}/.test(c))hasCode=true;}result.push(preserve?original:line?unit.repeat(Math.max(0,depth-leadingClose))+line:'');depth=Math.max(0,depth+opens-closes);}return result.join('\n');}
const api={pattern,matches,replace,diagnostics,format};if(typeof module!=='undefined')module.exports=api;else root.CBEditorModel=api;
})(globalThis);
