/* Upgrade the established CM5 contracts; every addon is bundled and loaded on demand. */
'use strict';
(()=>{
const M=CBEditorModel,$=id=>document.getElementById(id);let readyPromise,marks=[],findMarks=[],rawDiagnostics=[],identifierCache='',identifierWords=[],searchState={matches:[],index:-1},composing=false;
const scripts=['addon/comment/comment.js','addon/fold/foldcode.js','addon/fold/foldgutter.js','addon/fold/brace-fold.js','addon/fold/indent-fold.js','addon/fold/comment-fold.js','keymap/sublime.js'];
const load=path=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='vendor/codemirror/'+path;s.onload=resolve;s.onerror=()=>reject(Error('Bundled editor addon unavailable: '+path));document.head.append(s);});
const sizes=[11,12,13,14,15,16,18,20,22,24];
function ready(){return readyPromise??=scripts.reduce((p,name)=>p.then(()=>load(name)),Promise.resolve()).then(()=>{editor.setOption('foldGutter',true);editor.setOption('gutters',['breakpoints','CodeMirror-linenumbers','cb-errors','CodeMirror-foldgutter']);editor.setOption('configureMouse',e=>({addNew:e.ctrlKey||e.metaKey,rectangular:e.altKey}));editor.addKeyMap({'Ctrl-S':save,'Cmd-S':save,'Ctrl-F':find,'Cmd-F':find,'Ctrl-G':goLine,'Cmd-G':goLine,'Ctrl-Z':'undo','Ctrl-Y':'redo','Ctrl-Shift-Z':'redo','Ctrl-D':'duplicateLine','Cmd-D':'duplicateLine','Ctrl-/':'toggleComment','Cmd-/':'toggleComment','Alt-Up':'swapLineUp','Alt-Down':'swapLineDown','Ctrl-Shift-K':'deleteLine','Ctrl-Alt-D':'selectNextOccurrence','Ctrl-Alt-L':'splitSelectionByLine','Ctrl-Q':cm=>cm.foldCode(cm.getCursor()),Tab:cm=>cm.somethingSelected()?cm.indentSelection('add'):cm.replaceSelection(CBSettings.get().useTabs?'\t':' '.repeat(CBSettings.get().indent),'end','+input'),'Shift-Tab':cm=>cm.indentSelection('subtract'),Enter:smartEnter});apply();return true;});}
function smartEnter(cm){if(cm.somethingSelected()){CodeMirror.commands.newlineAndIndent(cm);return;}const pos=cm.getCursor(),line=cm.getLine(pos.line),before=line.slice(0,pos.ch),after=line.slice(pos.ch),s=CBSettings.get(),unit=s.useTabs?'\t':' '.repeat(s.indent),prefix=line.match(/^\s*/)[0];if(project.active.endsWith('.py')){let next=prefix;if(/:\s*(?:#.*)?$/.test(before))next+=unit;else if(/^\s*(return\b|raise\b|pass\s*$|break\s*$|continue\s*$)/.test(before))next=prefix.slice(0,Math.max(0,prefix.length-unit.length));cm.replaceSelection('\n'+next,'end','+input');}else if(/\{\s*$/.test(before)&&/^\s*}/.test(after)){cm.replaceSelection('\n'+prefix+unit+'\n'+prefix,'end','+input');cm.setCursor(pos.line+1,(prefix+unit).length);}else CodeMirror.commands.newlineAndIndent(cm);}
const keywords={c:'int char float double void unsigned signed long short const static volatile struct typedef enum union return if else for while do switch case break continue sizeof NULL printf scanf puts getchar putchar malloc calloc realloc free strlen strcmp strcpy strncpy memcpy memset fopen fclose fread fwrite stdio.h stdlib.h string.h math.h stdint.h stdbool.h assert.h',cpp:'auto bool char int float double void long const constexpr static class struct public private protected template typename namespace using virtual override noexcept return if else for while switch case break continue nullptr std cout cin endl string vector array map unordered_map set sort find begin end size push_back emplace_back iostream vector algorithm string array map set memory utility cmath',py:'def class return if elif else for while in import from as try except finally with lambda yield pass break continue raise print input range len enumerate zip sum min max sorted list dict set tuple str int float bool None True False open isinstance abs round any all numpy sympy mpmath math statistics collections itertools json random pathlib'};
const snippets={c:{for:'for (int i = 0; i < count; ++i) {\n    \n}',while:'while (condition) {\n    \n}',main:'int main(void) {\n    return 0;\n}',class:'typedef struct {\n    int value;\n} Item;'},cpp:{for:'for (const auto& item : items) {\n    \n}',while:'while (condition) {\n    \n}',main:'int main() {\n    return 0;\n}',class:'class Item {\npublic:\n    int value = 0;\n};'},py:{for:'for item in items:\n    print(item)',while:'while condition:\n    pass',main:'if __name__ == "__main__":\n    main()',class:'class Item:\n    def __init__(self, value):\n        self.value = value',def:'def calculate(value):\n    return value',try:'try:\n    value = int(input())\nexcept ValueError:\n    print("Enter a number")'}};
function completion(cm){const cursor=cm.getCursor(),line=cm.getLine(cursor.line),prefix=line.slice(0,cursor.ch).match(/[A-Za-z_][\w.]*$/)?.[0]||'',language=CBProjectsModel.language(project.active);const text=cm.getValue();if(identifierCache!==text){identifierCache=text;identifierWords=[...new Set(text.match(/\b[A-Za-z_]\w{1,50}\b/g)||[])].slice(0,5000);}const entries=[...new Set([...keywords[language].split(' '),...identifierWords])].filter(w=>w.startsWith(prefix)&&w!==prefix).sort().slice(0,40);const list=entries.map(text=>({text,displayText:text}));for(const [name,source]of Object.entries(snippets[language]))if(name.startsWith(prefix))list.unshift({text:name,displayText:name+' · snippet',hint:(editor,data)=>{editor.replaceRange(source,data.from,data.to,'complete');}});return {list,from:CodeMirror.Pos(cursor.line,cursor.ch-prefix.length),to:cursor};}
const dialog=document.createElement('dialog');dialog.id='editor-find';dialog.setAttribute('aria-label','Find and replace');document.body.append(dialog);
function find(){dialog.innerHTML='<h2>Find & replace</h2><label>Find<input id="find-query" autocomplete="off" spellcheck="false"></label><label>Replace<input id="find-replacement" autocomplete="off" spellcheck="false"></label><div class="find-options"><label><input id="find-regex" type="checkbox"> Regex</label><label><input id="find-case" type="checkbox"> Match case</label><label><input id="find-word" type="checkbox"> Whole word</label></div><p id="find-count" role="status">Enter a search term.</p><div class="editor-command-grid"><button id="find-prev">Previous</button><button id="find-next">Next</button><button id="find-replace">Replace</button><button id="find-all">Replace all</button><button data-overlay-close>Done</button></div>';for(const id of ['find-query','find-regex','find-case','find-word'])$(id).oninput=search;$( 'find-prev').onclick=()=>jumpMatch(-1);$('find-next').onclick=()=>jumpMatch(1);$('find-replace').onclick=()=>replace(false);$('find-all').onclick=()=>replace(true);CBOverlays.open(dialog,{onClose:()=>{findMarks.forEach(m=>m.clear());findMarks=[];}});$('find-query').focus();}
function options(){return {regex:$('find-regex').checked,caseSensitive:$('find-case').checked,wholeWord:$('find-word').checked};}
function search(){findMarks.forEach(m=>m.clear());findMarks=[];try{searchState={matches:M.matches(editor.getValue(),$('find-query').value,options()),index:-1};$('find-count').textContent=searchState.matches.length+' matches'+(searchState.matches.length===10000?' (display capped)':'');for(const m of searchState.matches.slice(0,500))findMarks.push(editor.markText(editor.posFromIndex(m.from),editor.posFromIndex(m.to),{className:'cb-search-match'}));}catch(e){searchState={matches:[],index:-1};$('find-count').textContent=e.message;}}
function jumpMatch(direction){const n=searchState.matches.length;if(!n)return;searchState.index=(searchState.index+direction+n)%n;const m=searchState.matches[searchState.index];editor.setSelection(editor.posFromIndex(m.from),editor.posFromIndex(m.to));editor.scrollIntoView(editor.getCursor(),40);$('find-count').textContent=(searchState.index+1)+' / '+n+' matches';}
function replace(all){if(editor.getOption('readOnly'))return;try{if(all)editor.setValue(M.replace(editor.getValue(),$('find-query').value,$('find-replacement').value,options()));else{if(searchState.index<0)jumpMatch(1);const m=searchState.matches[searchState.index];if(!m)return;const replacement=M.replace(m.text,$('find-query').value,$('find-replacement').value,options());editor.replaceRange(replacement,editor.posFromIndex(m.from),editor.posFromIndex(m.to),'replace');}search();}catch(e){$('find-count').textContent=e.message;}}
async function goLine(){const value=await modal('Go to line','Enter a line number between 1 and '+editor.lineCount()+'.',String(editor.getCursor().line+1));if(value!==null){const line=Math.min(editor.lineCount()-1,Math.max(0,(parseInt(value)||1)-1));editor.setCursor(line,0);editor.scrollIntoView(editor.getCursor(),40);editor.focus();}}
const tools=document.createElement('dialog');tools.id='editor-commands';tools.setAttribute('aria-label','Editor commands');document.body.append(tools);
async function commands(){await ready();tools.innerHTML='<h2>Your coding tools</h2><div class="editor-command-grid">'+[['find','Find / replace'],['goto','Go to line'],['toggleComment','Toggle comment'],['duplicateLine','Duplicate line'],['swapLineUp','Move line up'],['swapLineDown','Move line down'],['deleteLine','Delete line'],['selectNextOccurrence','Add next occurrence'],['splitSelectionByLine','Split selection into cursors'],['fold','Fold / unfold'],['format','Format indentation'],['wrap','Word wrap'],['spaces','Show whitespace'],['guides','Indent guides']].map(([id,label])=>`<button data-editor-command="${id}">${label}</button>`).join('')+'</div><label>Tab width<select id="editor-tab-width"><option>2</option><option>4</option><option>8</option></select></label><label>Indent with<select id="editor-indent-kind"><option value="spaces">Spaces</option><option value="tabs">Tabs</option></select></label><p class="small">Ctrl+S/F/G/Z/Y/D/slash · Alt+Up/Down · Ctrl+Shift+K · Ctrl+Alt+D adds a cursor · Alt-drag selects a column. Formatting changes indentation and trailing whitespace, not program syntax.</p><button data-overlay-close>Done</button>';$('editor-tab-width').value=CBSettings.get().indent;$('editor-indent-kind').value=CBSettings.get().useTabs?'tabs':'spaces';$('editor-tab-width').onchange=e=>CBSettings.set({indent:Number(e.target.value)});$('editor-indent-kind').onchange=e=>CBSettings.set({useTabs:e.target.value==='tabs'});tools.querySelectorAll('[data-editor-command]').forEach(b=>b.onclick=()=>command(b.dataset.editorCommand));CBOverlays.open(tools);}
async function command(id){await ready();if(id==='find'){CBOverlays.close(tools);find();return;}if(id==='goto'){CBOverlays.close(tools);goLine();return;}if(['wrap','spaces','guides'].includes(id)){const key={wrap:'wrap',spaces:'whitespace',guides:'indentGuides'}[id];CBSettings.set({[key]:!CBSettings.get()[key]});return;}if(editor.getOption('readOnly'))return;CBOverlays.close(tools);if(id==='format'){const s=CBSettings.get();editor.setValue(M.format(editor.getValue(),CBProjectsModel.language(project.active),s.indent,s.useTabs));}else if(id==='fold')editor.foldCode(editor.getCursor());else editor.execCommand(id);editor.focus();}
let whitespaceOverlay=null;
function apply(){const s=CBSettings.get();editor.setOption('tabSize',s.indent);editor.setOption('indentUnit',s.indent);editor.setOption('indentWithTabs',s.useTabs);editor.setOption('smartIndent',true);editor.getWrapperElement().classList.toggle('cb-indent-guides',s.indentGuides);editor.getWrapperElement().style.setProperty('--indent-size',s.indent+'ch');if(s.whitespace&&!whitespaceOverlay){whitespaceOverlay={token:stream=>{if(stream.peek()==='\t'){stream.next();return 'cb-tab';}if(stream.eatSpace())return 'cb-space';while(!stream.eol()&&!/\s/.test(stream.peek()))stream.next();return null;}};editor.addOverlay(whitespaceOverlay);}else if(!s.whitespace&&whitespaceOverlay){editor.removeOverlay(whitespaceOverlay);whitespaceOverlay=null;}}
editor.on('renderLine',(_,line,element)=>{const leading=line.text.match(/^\s*/)[0].replace(/\t/g,' '.repeat(CBSettings.get().indent)).length;element.style.setProperty('--guide-width',leading+'ch');});
editor.getInputField().addEventListener('compositionstart',()=>{composing=true;editor.state.cbComposing=true;editor.state.completionActive?.close();});editor.getInputField().addEventListener('compositionend',()=>{composing=false;editor.state.cbComposing=false;});
function clearDiagnostics(){marks.forEach(m=>m.clear());marks=[];editor.clearGutter('cb-errors');}
function paintDiagnostics(){clearDiagnostics();const list=rawDiagnostics.filter(d=>d.file===project.active||d.file.endsWith('/'+project.active));for(const d of list){const line=Math.max(0,Math.min(editor.lineCount()-1,d.line-1)),ch=Math.max(0,Math.min(editor.getLine(line).length-1,d.column-1));if(editor.getLine(line).length)marks.push(editor.markText({line,ch},{line,ch:Math.min(editor.getLine(line).length,ch+Math.max(1,editor.getLine(line).slice(ch).match(/^\w+/)?.[0].length||1))},{className:'cb-diagnostic',title:d.raw}));const marker=document.createElement('button');marker.type='button';marker.className='cb-error-marker';marker.textContent=d.severity==='warning'?'△':'!';marker.setAttribute('aria-label',d.raw);marker.onclick=()=>diagnosticSheet(d);editor.setGutterMarker(line,'cb-errors',marker);}}
function diagnosticSheet(d){const panel=document.createElement('dialog');panel.setAttribute('aria-label','Compiler diagnostic');const hint=CBDiagnostics.explain(d.raw);panel.innerHTML='<h2></h2><p></p><pre></pre><button>Go to line '+d.line+'</button>';panel.querySelector('h2').textContent=hint.title;panel.querySelector('p').textContent=hint.explanation;panel.querySelector('pre').textContent=d.file+':'+d.line+':'+d.column+' '+d.raw;panel.querySelector('button').onclick=()=>{CBOverlays.close(panel);document.body.classList.remove('output-mode');if(project.files.some(f=>f.name===d.file))select(d.file);editor.setCursor(d.line-1,d.column-1);editor.scrollIntoView(editor.getCursor(),40);editor.focus();};document.body.append(panel);panel.addEventListener('close',()=>panel.remove(),{once:true});CBOverlays.open(panel);}
window.addEventListener('cb:code-error',e=>{rawDiagnostics=M.diagnostics(e.detail?.text||'');ready().then(paintDiagnostics);});window.addEventListener('cb:file-selected',paintDiagnostics);window.addEventListener('cb:settings',apply);editor.on('change',()=>{if(!loading&&rawDiagnostics.length){rawDiagnostics=[];clearDiagnostics();}});
const button=document.createElement('button');button.id='editor-pro-open';button.textContent='Editor tools';button.onclick=commands;$('menu').append(button);$('edit-actions').querySelectorAll('button').forEach(b=>{if(b.textContent==='Find')b.onclick=find;});
const symbols=$('symbols');for(const [label,cmd]of [['←','goCharLeft'],['→','goCharRight'],['↑','goLineUp'],['↓','goLineDown']]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',cmd);b.onclick=()=>{editor.focus();editor.execCommand(cmd);};symbols.append(b);}
document.addEventListener('keydown',e=>{if(e.defaultPrevented||!(e.ctrlKey||e.metaKey)||CBOverlays.depth()||$('app').classList.contains('academy-mode'))return;const key=e.key.toLowerCase();if(key==='s'){e.preventDefault();save();}else if(key==='f'){e.preventDefault();find();}else if(key==='g'){e.preventDefault();goLine();}});
window.CBEditorPro={ready,command,find,goLine,completion,parseDiagnostics:M.diagnostics,diagnostics:()=>rawDiagnostics,composing:()=>composing};window.addEventListener('cb:navigate',e=>{if(e.detail.view==='code')ready().catch(error=>showStatus(error.message));});
})();
