const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {serve}=require('../desktop/server.cjs');
(async()=>{const hosted=await serve(path.resolve(__dirname,'../app'));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
await page.addInitScript(()=>{if(!localStorage.getItem('codebridge.projects.v1'))localStorage.setItem('codebridge.project',JSON.stringify({name:'Original project',active:'main.c',files:[{name:'main.c',content:'#include <stdio.h>\nint main(){puts("FIRST");}'},{name:'second.c',content:'#include <stdio.h>\nint main(){puts("SECOND");}'}],breakpoints:{}}));});
await page.goto(hosted.url);await page.waitForFunction(()=>!!window.CBProjects);await page.waitForSelector('#upgrade-splash',{state:'detached'});await page.click('[data-view=code]');assert.equal(await page.locator('#project-hub').isVisible(),true);assert.equal(await page.locator('#editor-area').isVisible(),false);assert.equal(await page.locator('#project-scope').inputValue(),'file');await page.screenshot({path:'.artifacts/075-projects.png'});
await page.click('[data-file="second.c"]');await page.click('#run');await page.waitForFunction(()=>document.getElementById('status').textContent==='Completed successfully',{},{timeout:120000});assert.match(await page.textContent('#output'),/SECOND/);assert.doesNotMatch(await page.textContent('#diagnostics'),/duplicate symbol/);
await page.click('#back-editor');await page.click('#editor-home');await page.click('[data-file="main.c"]');await page.click('#run');await page.waitForFunction(()=>document.getElementById('status').textContent==='Completed successfully',{},{timeout:120000});assert.match(await page.textContent('#output'),/FIRST/);await page.click('#back-editor');
const downloadPromise=page.waitForEvent('download');await page.click('#editor-save');const downloaded=await downloadPromise;assert.equal(downloaded.suggestedFilename(),'main.c');assert.match(fs.readFileSync(await downloaded.path(),'utf8'),/FIRST/);
await page.click('#editor-home');await page.click('#create-project');await page.fill('#new-project-name','Vector workshop');await page.selectOption('#new-project-language','cpp');await page.click('#project-create-form button[value=create]');assert.equal(await page.locator('.project-card').count(),2);await page.selectOption('#project-standard','c++14');await page.selectOption('#project-optimization','O2');await page.selectOption('#project-scope','project');
await page.click('#open-editor');await page.evaluate(()=>{editor.setValue('#include <iostream>\n#include "sum.h"\nint main(){std::cout<<sum(20,22); }');addFileUnique('sum.h','int sum(int,int);');addFileUnique('sum.cpp','int sum(int a,int b){return a+b;}');select('main.cpp');});await page.click('#run');await page.waitForFunction(()=>document.getElementById('status').textContent==='Completed successfully',{},{timeout:120000});assert.match(await page.textContent('#output'),/42/);await page.click('#back-editor');await page.click('#editor-home');
await page.click('#create-project');await page.fill('#new-project-name','Python notebook');await page.selectOption('#new-project-language','py');assert.match(await page.locator('#new-project-runtime').textContent(),/Python 3.12/);await page.click('#project-create-form button[value=create]');await page.click('#open-editor');await page.evaluate(()=>editor.setValue('print("SAVED PYTHON")'));const pythonId=await page.evaluate(()=>project.id);await page.reload();await page.waitForFunction(()=>!!window.CBProjects);assert.equal(await page.evaluate(()=>project.id),pythonId);assert.equal(await page.evaluate(()=>current().content),'print("SAVED PYTHON")');await page.click('[data-view=code]');assert.equal(await page.locator('.project-card').count(),3);
const library=await page.evaluate(()=>CBProjects.getLibrary());const cpp=library.projects.find(p=>p.name==='Vector workshop');assert.equal(cpp.compiler.cppStandard,'c++14');assert.equal(cpp.compiler.optimization,'O2');assert.equal(cpp.files.length,3);assert.equal(library.projects.find(p=>p.name==='Original project').files[1].content.includes('SECOND'),true);
await page.click('#open-editor');await page.evaluate(()=>editor.focus());await page.setViewportSize({width:390,height:420});await page.waitForFunction(()=>document.body.classList.contains('editor-typing'));assert.equal(await page.locator('#symbols').isVisible(),true);assert.ok(await page.locator('#symbols').evaluate(n=>n.scrollWidth>n.clientWidth));await page.locator('#symbols').evaluate(n=>n.scrollLeft=n.scrollWidth);await page.locator('#symbols button[data-insert="?"]').click();assert.equal(await page.evaluate(()=>editor.hasFocus()),true);await page.screenshot({path:'.artifacts/075-keyboard.png'});
await page.evaluate(()=>editor.getInputField().blur());await page.setViewportSize({width:390,height:844});await page.evaluate(()=>CodeBridgeAcademy.navigate('learn'));await page.click('[data-course=cpp]');await page.screenshot({path:'.artifacts/075-learning-path.png'});assert.equal(await page.locator('.unit-banner').count(),3);assert.equal(await page.locator('.path-start').count(),1);assert.ok(await page.locator('.node-glyph').count()>10);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.evaluate(()=>{CBSettings.set({motion:false});});assert.equal(await page.locator('.path-node.next').first().evaluate(n=>getComputedStyle(n).animationName),'none');assert.deepEqual(errors,[]);
console.log('PASS real duplicate-main current-file runs, project linking, source extension export, independent saved projects/settings, reload, keyboard symbols and unit path');
}finally{await browser.close();hosted.server.close();}})().catch(e=>{console.error(e);process.exit(1)});
