const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const {serve}=require('../desktop/server.cjs');
(async()=>{const hosted=await serve(path.resolve(__dirname,'../app'));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:740}});try{
 await page.goto(hosted.url);await page.waitForFunction(()=>!!window.CBTerminal);await page.click('[data-view=code]');
 async function code(name,content){await page.evaluate(({name,content})=>{project={name:'Terminal test',active:name,files:[{name,content}],breakpoints:{}};loading=true;editor.setValue(content);loading=false;select(name);document.getElementById('stdin').value='';CBSettings.set({roast:false});},{name,content});}
 async function waiting(){await page.waitForFunction(()=>CBTerminal.waiting,{},{timeout:120000});}
 async function send(text){await page.fill('#terminal-line',text);await page.press('#terminal-line','Enter');}
 async function done(){await page.waitForFunction(()=>document.getElementById('status').textContent==='Completed successfully',{},{timeout:120000});}
 await code('main.c','#include <stdio.h>\nint main(){int a,b;printf("First: ");scanf("%d",&a);printf("Second: ");scanf("%d",&b);printf("Sum=%d\\n",a+b);return 0;}');await page.click('#run');await waiting();assert.equal(await page.textContent('#output'),'First: ');await send('12');await waiting();assert.match(await page.textContent('#output'),/First: 12\nSecond: /);await send('30');await done();assert.match(await page.textContent('#output'),/Sum=42/);
 await code('main.cpp','#include <iostream>\n#include <string>\nint main(){std::string name;std::cout<<"Name: ";std::getline(std::cin,name);std::cout<<"Hello "<<name<<"\\n";}');await page.click('#run');await waiting();await send('Dost سلام');await done();assert.match(await page.textContent('#output'),/Hello Dost سلام/);
 await code('main.py','name=input("Name: ")\na=int(input("Number: "))\nprint(name,a*2)');await page.click('#run');await waiting();assert.equal(await page.textContent('#output'),'Name: ');await send('Dost سلام');await waiting();await page.setViewportSize({width:360,height:400});assert.equal(await page.locator('#terminal-line').isVisible(),true);assert.ok(await page.evaluate(()=>{const r=document.getElementById('terminal-line').getBoundingClientRect();return r.bottom<=innerHeight&&r.left>=0;}));await page.screenshot({path:'.artifacts/terminal-keyboard.png'});await send('21');await done();assert.match(await page.textContent('#output'),/Dost سلام 42/);
 await code('main.c','#include <stdio.h>\nint main(){int c,n=0;while((c=getchar())!=EOF)n++;printf("bytes=%d",n);}');await page.click('#run');await waiting();await send('abc');await waiting();await page.click('#terminal-eof');await done();assert.match(await page.textContent('#output'),/bytes=4/);
 await code('main.py','input("Stop here: ")');await page.click('#run');await waiting();await page.click('#stop');assert.equal(await page.textContent('#status'),'Stopped');await page.click('#run');await waiting();await send('again');await done();
 await code('main.py','print(42, end="")');await page.click('#run');await done();assert.equal(await page.textContent('#output'),'42');
 await page.setViewportSize({width:390,height:740});await page.click('#back-editor');await code('main.cpp','');await page.evaluate(()=>CBEditor.insert('{'));assert.equal(await page.evaluate(()=>editor.getValue()),'{}');assert.equal(await page.evaluate(()=>editor.getCursor().ch),1);await page.keyboard.press('Enter');assert.match(await page.evaluate(()=>editor.getValue()),/\{\n +\n\}/);await page.screenshot({path:'.artifacts/terminal-editor.png'});
 await code('main.py','print(1/0)');await page.evaluate(()=>CBSettings.set({roast:true}));await page.click('#run');await page.waitForFunction(()=>!document.getElementById('bit-reaction').hidden,{},{timeout:120000});assert.equal(await page.evaluate(()=>document.getElementById('bit-panel').open),false);await page.screenshot({path:'.artifacts/terminal-bit.png'});
 console.log('PASS interactive scanf, cin/getline UTF-8, Python prompts, EOF, Stop/restart, keyboard viewport, bracket pairing, nonblocking Bit');
 }finally{console.log('Status:',await page.textContent('#status'));console.log('Diagnostics:',await page.textContent('#diagnostics'));await browser.close();hosted.server.close();}})().catch(e=>{console.error(e);process.exit(1)});
