const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {serve}=require('../desktop/server.cjs');
(async()=>{const hosted=await serve(path.resolve(__dirname,'../app'));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 // A real 0.7-shaped save: original lesson completion, balance and draft survive update.
 await page.addInitScript(()=>{if(!localStorage.getItem('codebridge.progress.v1'))localStorage.setItem('codebridge.progress.v1',JSON.stringify({version:1,name:'Dost',completed:['c-1','c-2','c-3','c-4','c-5'],quiz:['c-1'],xp:250,coins:60,streak:1,lastActive:null,lastReward:null,days:{},claims:[],drafts:{'c-1':'saved original draft'},lastLesson:'c-5'}));});
 await page.goto(hosted.url);await page.waitForFunction(()=>!!window.CBUpgrade);await page.waitForSelector('#upgrade-splash',{state:'detached'});await page.waitForSelector('.bit-sprite');
 assert.equal(await page.locator('.bottom-nav button').count(),5);assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().drafts['c-1']),'saved original draft');
 await page.screenshot({path:'.artifacts/071-home.png'});
 await page.evaluate(()=>CBUpgrade.chooseLocale('ur'));assert.equal(await page.getAttribute('html','dir'),'rtl');await page.click('[data-view=code]');assert.equal(await page.evaluate(()=>editor.getOption('direction')),'ltr');await page.evaluate(()=>editor.setValue('print("سلام")'));assert.equal(await page.evaluate(()=>editor.getValue()),'print("سلام")');
 await page.evaluate(()=>CBUpgrade.setFocus(true));assert.equal(await page.locator('header').isVisible(),false);await page.click('#focus-exit');assert.equal(await page.locator('header').isVisible(),true);await page.screenshot({path:'.artifacts/071-urdu-editor.png'});
 await page.reload();await page.waitForFunction(()=>!!window.CBUpgrade);await page.waitForSelector('#upgrade-splash',{state:'detached'});assert.equal(await page.evaluate(()=>CBUpgrade.getLocale()),'ur');await page.evaluate(()=>CBUpgrade.chooseLocale('zh-Hans'));await page.screenshot({path:'.artifacts/071-chinese-home.png'});await page.evaluate(()=>CBUpgrade.chooseLocale('en'));
 await page.click('[data-view=learn]');await page.click('[data-course=c]');assert.equal(await page.locator('[data-lesson=c-5]').isDisabled(),false,'existing next-stage mastery remains accessible');await page.click('[data-lesson=c-memory-1]');await page.click('[data-answer="0"]');
 // Starter produces correct mathematical output but leaks: no reward should be granted.
 const before=await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp);await page.click('#check-lesson');await page.waitForFunction(()=>document.querySelector('#lesson-feedback').classList.contains('failure'),{},{timeout:120000});assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp),before);
 await page.evaluate(()=>document.querySelector('.lesson-editor .CodeMirror').CodeMirror.setValue(CBCourses[0].lessons.find(l=>l.id==='c-memory-1').solution));await page.click('#check-lesson');await page.waitForSelector('#boss-chest[open]',{timeout:180000});assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp),before+200);await page.screenshot({path:'.artifacts/071-boss-reward.png'});await page.click('#boss-chest button');
 await page.click('#check-lesson');await page.waitForFunction(()=>!document.getElementById('check-lesson').disabled,{},{timeout:180000});assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp),before+200,'replay cannot duplicate XP');
 await page.click('[data-view=profile]');assert.match(await page.textContent('#memory-badges'),/♜ C/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS original 0.7 save/UI, locale persistence, LTR source, focus toggle, boss failure/pass/replay and badge');
 }finally{await browser.close();hosted.server.close();}})().catch(e=>{console.error(e);process.exit(1)});
