const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {serve}=require('../desktop/server.cjs');
(async()=>{const hosted=await serve(path.resolve(__dirname,'../app'));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 // A real 0.7-shaped save: original lesson completion, balance and draft survive update.
 await page.addInitScript(()=>{if(!localStorage.getItem('codebridge.progress.v1'))localStorage.setItem('codebridge.progress.v1',JSON.stringify({version:1,name:'Dost',completed:['c-1','c-2','c-3','c-4','c-5'],quiz:['c-1'],xp:250,coins:60,streak:1,lastActive:null,lastReward:null,days:{},claims:[],drafts:{'c-1':'saved original draft'},lastLesson:'c-5'}));});
 await page.route('**/app.js',async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();});const navigation=page.goto(hosted.url);await page.waitForSelector('#upgrade-splash');assert.equal(await page.locator('header').isVisible(),false);await page.screenshot({path:'.artifacts/072-splash.png'});await navigation;await page.waitForFunction(()=>!!window.CBUpgrade);await page.waitForSelector('#upgrade-splash',{state:'detached'});await page.waitForSelector('.bit-sprite');
 assert.equal(await page.locator('.bottom-nav button').count(),5);assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().drafts['c-1']),'saved original draft');
 await page.screenshot({path:'.artifacts/071-home.png'});
 assert.equal(await page.locator('[data-locale],#language-open,#first-language').count(),0);
 await page.click('[data-view=code]');assert.equal(await page.locator('footer').isVisible(),false);assert.equal(await page.locator('.bottom-nav').isVisible(),false);
 const dimensions=await page.evaluate(()=>({editor:document.getElementById('editor-area').getBoundingClientRect().height,gutter:document.querySelector('.CodeMirror-gutters').getBoundingClientRect().width,header:document.querySelector('header').getBoundingClientRect().height}));assert.ok(dimensions.editor>700,JSON.stringify(dimensions));assert.ok(dimensions.gutter<40,JSON.stringify(dimensions));assert.ok(dimensions.header<=36);
 await page.screenshot({path:'.artifacts/072-editor.png'});
 await page.evaluate(()=>editor.focus());await page.setViewportSize({width:390,height:420});await page.waitForFunction(()=>document.body.classList.contains('editor-typing'));
 assert.equal(await page.locator('header').isVisible(),false);assert.equal(await page.locator('footer').isVisible(),false);assert.equal(await page.locator('.bottom-nav').isVisible(),false);assert.ok(await page.evaluate(()=>document.getElementById('editor-area').getBoundingClientRect().height)>370);await page.screenshot({path:'.artifacts/072-editor-keyboard.png'});
 await page.evaluate(()=>editor.getInputField().blur());await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>!document.body.classList.contains('keyboard-open'));await page.click('#editor-home');
 await page.click('[data-view=learn]');await page.click('[data-course=c]');assert.ok(await page.locator('.node-map svg .path-link').count()>5);await page.screenshot({path:'.artifacts/072-path.png'});assert.equal(await page.locator('[data-lesson=c-5]').isDisabled(),false,'existing next-stage mastery remains accessible');await page.click('[data-lesson=c-memory-1]');await page.click('[data-answer="0"]');
 // Starter produces correct mathematical output but leaks: no reward should be granted.
 const before=await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp);await page.click('#check-lesson');await page.waitForFunction(()=>document.querySelector('#lesson-feedback').classList.contains('failure'),{},{timeout:120000});assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp),before);
 await page.evaluate(()=>document.querySelector('.lesson-editor .CodeMirror').CodeMirror.setValue(CBCourses[0].lessons.find(l=>l.id==='c-memory-1').solution));await page.click('#check-lesson');await page.waitForSelector('#boss-chest[open]',{timeout:180000});assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp),before+200);await page.screenshot({path:'.artifacts/071-boss-reward.png'});await page.click('#boss-chest button');
 await page.click('#check-lesson');await page.waitForFunction(()=>!document.getElementById('check-lesson').disabled,{},{timeout:180000});assert.equal(await page.evaluate(()=>CodeBridgeAcademy.getProgress().xp),before+200,'replay cannot duplicate XP');
 await page.click('[data-view=profile]');assert.match(await page.textContent('#memory-badges'),/♜ C/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS original 0.7 save/UI, English-only UI, circular path, compact editor and keyboard, boss failure/pass/replay and badge');
 }finally{await browser.close();hosted.server.close();}})().catch(e=>{console.error(e);process.exit(1)});
