(function(root){
'use strict';
const rules=[
[/Compiler runtime limit/i,'Compiler runtime limit','The bundled compiler exceeded its own WebAssembly limits while building this source. This does not prove your program is wrong. Reduce a very large template/header workload or use a native toolchain for this project.','Try a smaller source file to isolate the compiler limit.'],
[/expected ['"]?;|expected ';'/i,'Missing semicolon','C and C++ statements usually end with a semicolon. Inspect the reported line and the line immediately above it.','int total = 42;'],
[/undeclared identifier|was not declared|NameError/i,'Unknown name','This name has not been declared in the current scope. Check spelling, capitalization, imports and where the variable is created.','Declare the variable before using it; check the exact name.'],
[/IndentationError|TabError|expected an indented block/i,'Indentation mismatch','Python uses indentation to group statements. Use consistent spaces and indent the body after if, for, while, def and class.','if ready:\n    print("Ready")'],
[/SyntaxError|invalid syntax/i,'Syntax error','The parser cannot read this statement. Check colons, closing brackets, quotes and the preceding line.','if score > 10:\n    print(score)'],
[/ZeroDivisionError|division by zero/i,'Division by zero','The divisor is zero. Check or validate it before division; decide how your program should handle zero.','if divisor != 0:\n    result = value / divisor'],
[/IndexError|out of bounds|memory access out of bounds/i,'Index or memory error','An index or pointer may refer outside its valid range. For a sequence of length n, valid indices run from 0 through n - 1. Check empty collections too.','if 0 <= index < len(values):\n    print(values[index])'],
[/TypeError|incompatible.*type|invalid operands/i,'Type mismatch','The operation received values with incompatible types. Inspect the types and convert explicitly only when that matches your intent.','age = int(input())  # input() returns text'],
[/ValueError/i,'Invalid value','The type may be correct but the value is not accepted—for example int("hello"). Validate input and handle invalid values.','try:\n    number = int(input())\nexcept ValueError:\n    print("Enter a whole number")'],
[/ModuleNotFoundError|No module named|file not found/i,'Missing module or header','Check the file name and import/include path. Python includes NumPy, SymPy and mpmath. C and C++ include cJSON.h. Other native dependencies are not automatically available.','Python: import numpy as np\nC++: #include <cJSON.h>'],
[/undefined symbol|undefined reference/i,'Linker error','A declaration was found but the implementation could not be linked. Include the matching source file in your project and check the function signature.','Keep one main() per C/C++ project; add every required .c or .cpp source file.'],
[/redefinition|duplicate symbol/i,'Duplicate definition','The same symbol is defined more than once. Check for multiple main functions or function bodies defined in headers without appropriate guards/inline.','Each executable project needs exactly one main().'],
[/EOFError|EOF when reading/i,'Input ran out','The input stream ended before the program finished reading. Run again and enter the requested values in the terminal. Use EOF only when finished.','Enter one line for each input() call, or preload both lines.'],
[/expected.*[)}]|unterminated|missing terminating/i,'Unclosed bracket or string','A bracket or quoted string was opened without its matching closing character. Start at the reported line, then inspect earlier lines.','Match (), [] and {}. Close each string with the same quote type.'],
[/Output limit/i,'Too much output','An output loop exceeded the app limit. Check that the loop stops and reduce printed data.','Print a summary or a small sample instead of every iteration.']
];
const roasts=[
'Bhai, bug ne yahan permanent address banwa liya. Line check kar!','Compiler keh raha hai: mujhe maaf karo, yeh kya likh diya!','Yeh loop hai ya load shedding? Khatam hi nahi ho raha.','Wah ustad, code ko bhi Monday wali feeling aa gayi.','Logic ka tyre puncture hai. Hint se hawa bharte hain.','Code ki biryani mein bracket ka namak reh gaya!','Bug ko VIP treatment mat de. Pakar ke bahar nikaal.','Compiler ki cheekh sun raha hai? Neeche error padh le bhai.','Yeh syntax ne toh scene hi ulta kar diya. Chal theek karte hain.','Code ne kaha: aaj mera mood nahi. Hum ne kaha: test toh hoga!','Bhai, copy paste ko bhi samajh chahiye. Pehli error dekh.','Variable gum hai, missing poster lagao ya spelling check karo!','Chai garam, compiler naram nahi. Rules follow kar ustad.','Is bug ka confidence dekho, seedha production jaana chahta hai.','Bakwaas logic ki chhutti. Ek chhota test likh ab.','Code ki dhulai hogi, teri nahi. Hint padh aur dobara chala.','Bhai yeh bracket bhi rishtedaar hai, jora saath rakho!','Wah, error ka world tour! Pehli line se safar shuru kar.','Bug ko itni mohabbat mat de, fix kar ke alvida keh.','Compiler ke sabr ka imtehan band kar, semicolon de de!',

'Bhai, semicolon ko chhutti pe bhej diya? Compiler tera rishtedaar nahi jo khud samajh le!',
'Yeh code hai ya biryani mein ketchup? Chal, pehle error wali line seedhi kar.',
'Code ne phir se dhoka de diya, yaar. Kachra logic saaf karte hain—tu kar lega!',
'Wah ustad, bug ko permanent naukri de di? Ab isko nikaalte hain.',
'Bakwas syntax ne compiler ka dimagh paka diya. Neeche wali hint dekh, phir dobara chala.'
];
function explain(text){const line=String(text).match(/(?:^|\n)([^\n:]+):(\d+):(\d+):/)||String(text).match(/File "([^"]+)", line (\d+)/);const match=rules.find(r=>r[0].test(text));return {title:match?.[1]||'Let’s inspect this error',explanation:match?.[2]||'Read the first error before the later ones: one early mistake can cause many follow-up messages. Compare the reported line with your intended behavior.',example:match?.[3]||'Try a smaller input or isolate the failing statement. Then run again.',file:line?.[1]||'',line:line?Number(line[2]):null};}
function roast(seed=0,title=''){if(title==='Missing semicolon'&&seed%3===0)return 'Semicolon kidhar hai bhai? Compiler andaza nahi lagata!';if(title==='Division by zero')return 'Zero se divide? Bhai, calculator ko bhi chakkar aa gaye! Pehle divisor check kar.';return roasts[1+Math.abs(seed)%(roasts.length-1)];}
const api={explain,roast};if(typeof module!=='undefined')module.exports=api;else root.CBDiagnostics=api;
})(globalThis);
