
'use strict';
(()=>{
const $=document.getElementById.bind(document);let lastError='',roastIndex=Number(localStorage.getItem('codebridge.bit.turn')||0);
const face='<svg class="bit-face" viewBox="0 0 100 80" aria-label="Bit mascot" role="img"><rect x="10" y="10" width="80" height="58" rx="22" fill="currentColor"/><rect x="21" y="23" width="58" height="31" rx="12" fill="var(--bg)"/><path class="bit-eyes" d="M31 33l10 6 M59 39l10-6" stroke="currentColor" stroke-width="5"/><path d="M42 47q8 10 16 0" stroke="currentColor" fill="none" stroke-width="3"/></svg>';
const panelEl=document.createElement('dialog');panelEl.id='bit-panel';panelEl.setAttribute('aria-label','Bit coding companion');panelEl.innerHTML='<div class="bit-header"><h2>Bit · code buddy</h2><button id="bit-close" aria-label="Close Bit">✕</button></div><div id="bit-content">'+face+'<p id="bit-roast" hidden></p><h3 id="bit-title">Let’s work through it.</h3><p id="bit-explanation">Run your code for error guidance. Bit uses our own written rules and dialogue, without an AI model.</p><pre id="bit-example" hidden></pre><button id="bit-jump" hidden>Go to error line</button><h3>Banter with Bit</h3><p>Scripted Roman Urdu replies. Turn on roast mode in Settings for jokes after errors.</p><form id="bit-chat"><input id="bit-prompt" aria-label="Message to Bit" placeholder="Say hello, ask for help, or challenge Bit" autocomplete="off"><button id="bit-ask">Reply</button></form><p id="bit-ai-result" aria-live="polite">Bhai, code laao. Chai baad mein!</p><p id="power-help">Offline libraries: NumPy, SymPy, mpmath and cJSON. Bit’s explanations are preset guidance—not a trained model or automatic code fixes.</p></div>';document.body.append(panelEl);
const card=document.createElement('div');card.id='bit-reaction';card.hidden=true;card.innerHTML=face+'<p></p><button aria-label="Dismiss Bit reaction">✕</button>';document.querySelector('.console-heading').after(card);card.querySelector('button').onclick=()=>card.hidden=true;
function joke(title=''){const text=CBDiagnostics.roast(roastIndex++,title);localStorage.setItem('codebridge.bit.turn',String(roastIndex));return text;}
function openBit(error=lastError){if(error){const hint=CBDiagnostics.explain(error);$('bit-title').textContent=hint.title;$('bit-explanation').textContent=hint.explanation;$('bit-example').textContent=hint.example;$('bit-example').hidden=false;$('bit-jump').hidden=!hint.line||!project.files.some(f=>hint.file===f.name||hint.file==='/project/'+f.name);$('bit-jump').onclick=()=>{panelEl.close();document.body.classList.remove('output-mode');const target=project.files.find(f=>hint.file===f.name||hint.file==='/project/'+f.name);if(target)select(target.name);editor.setCursor(Math.max(0,Math.min(hint.line-1,editor.lineCount()-1)),0);editor.scrollIntoView(editor.getCursor(),80);editor.focus();};$('bit-roast').hidden=!CBSettings.get().roast;if(CBSettings.get().roast)$('bit-roast').textContent=joke(hint.title);}if(!panelEl.open)panelEl.showModal();}
$('bit-close').onclick=()=>panelEl.close();
$('bit-chat').onsubmit=e=>{e.preventDefault();const q=$('bit-prompt').value.trim();if(!q)return;let answer;if(/help|madad|error|bug|fix/i.test(q))answer=lastError?CBDiagnostics.explain(lastError).explanation:'Run your program first, then open Bit beside the error. I can explain common diagnostics.';else if(/hello|salam|hi\b/i.test(q))answer='Walaikum salam, coder! Aaj bugs ki chhutti karwaate hain.';else if(/thanks|shukriya/i.test(q))answer='Khush raho ustad! Ab woh fix test bhi kar lo.';else answer=CBSettings.get().roast?joke():'I use scripted replies. Ask for help, say hello, or enable roast mode for banter.';$('bit-ai-result').textContent=answer;$('bit-prompt').value='';};
window.BitAI={open:openBit,isBusy:()=>false};
window.addEventListener('cb:code-error',e=>{let text=e.detail?.text||'';if(e.detail?.phase==='build'&&/memory access out of bounds|unreachable/i.test(text))text='Compiler runtime limit\n'+text;lastError=text;const hint=CBDiagnostics.explain(text);$('bit-error-button').hidden=false;$('bit-error-button').textContent='✦ Bit: '+hint.title;if(CBSettings.get().roast){card.hidden=false;card.dataset.mood=['angry','laugh','confused'][roastIndex%3];card.querySelector('p').textContent=joke(hint.title);}});
window.addEventListener('cb:run-done',()=>{lastError='';$('bit-error-button').hidden=true;$('bit-title').textContent='Your last run completed.';$('bit-explanation').textContent='Check the output against what you expected, and try another input.';$('bit-example').hidden=true;$('bit-jump').hidden=true;$('bit-roast').hidden=true;card.hidden=true;});
window.addEventListener('cb:settings',()=>{if(!CBSettings.get().roast)card.hidden=true;});
const errorButton=document.createElement('button');errorButton.id='bit-error-button';errorButton.hidden=true;errorButton.onclick=()=>openBit();document.querySelector('.console-heading').append(errorButton);
const bar=document.createElement('div');bar.id='editor-tools';bar.innerHTML='<button id="zoom-out" aria-label="Zoom out editor">A−</button><span id="zoom-label"></span><button id="zoom-in" aria-label="Zoom in editor">A+</button><button id="suggest-code">Suggest</button><button id="insert-snippet">Snippet</button><button id="bit-open">✦ Ask Bit</button>';document.querySelector('.workspace').insertBefore(bar,$('editor-area'));
const sizes=[11,12,13,14,15,16,18,20,22,24];function zoom(delta){const index=sizes.indexOf(CBSettings.get().fontSize);CBSettings.set({fontSize:sizes[Math.max(0,Math.min(sizes.length-1,index+delta))]});}
$('zoom-in').onclick=()=>zoom(1);$('zoom-out').onclick=()=>zoom(-1);$('bit-open').onclick=()=>openBit();function showZoom(){$('zoom-label').textContent=CBSettings.get().fontSize+'px';}showZoom();window.addEventListener('cb:settings',showZoom);
const words={python:'def class return if elif else for while in import from as try except finally with lambda yield print input range len enumerate zip sum min max sorted list dict set tuple str int float bool None True False numpy sympy mpmath',c:'int char float double void long short unsigned signed struct typedef enum const static return if else for while do switch case break continue sizeof printf scanf malloc free strlen strcmp memcpy NULL cJSON_Parse cJSON_Delete',cpp:'auto bool int char float double void long const constexpr static class struct public private protected template typename namespace using return if else for while switch case break continue nullptr std cout cin endl string vector array map unordered_map set sort find begin end size push_back emplace_back cJSON_Parse cJSON_Delete cJSON_CreateObject'};
function hints(cm){const cursor=cm.getCursor(),line=cm.getLine(cursor.line),match=line.slice(0,cursor.ch).match(/[A-Za-z_]\w*$/),prefix=match?.[0]||'';const language=project.active.endsWith('.py')?'python':project.active.endsWith('.c')?'c':'cpp';const identifiers=(cm.getValue().slice(0,100000).match(/\b[A-Za-z_]\w{1,50}\b/g)||[]);const list=[...new Set([...words[language].split(' '),...identifiers])].filter(w=>w!==prefix&&w.startsWith(prefix)).sort().slice(0,40);return {list,from:CodeMirror.Pos(cursor.line,cursor.ch-prefix.length),to:cursor};}
function suggest(){if(editor.getOption('readOnly'))return;editor.showHint({hint:hints,completeSingle:false});}
$('suggest-code').onclick=suggest;editor.addKeyMap({'Ctrl-Space':suggest,'Ctrl-=':()=>zoom(1),'Ctrl--':()=>zoom(-1)});editor.on('inputRead',(cm,change)=>{if(!CBSettings.get().suggestions||change.origin!=='+input')return;const cur=cm.getCursor(),type=cm.getTokenAt(cur).type||'';if(!/comment|string/.test(type)&&/[A-Za-z_]\w+$/.test(cm.getLine(cur.line).slice(0,cur.ch)))suggest();});
$('insert-snippet').onclick=async()=>{if(editor.getOption('readOnly'))return;const py=project.active.endsWith('.py'),c=project.active.endsWith('.c');const snippets=py?{'for':'for item in items:\n    print(item)\n','function':'def calculate(value):\n    return value * 2\n','numpy':'import numpy as np\nvalues = np.array([1, 2, 3])\nprint(values.mean())\n','sympy':'import sympy as sp\nx = sp.symbols("x")\nprint(sp.factor(x**2 - 1))\n'}:c?{'for':'for (int i = 0; i < 10; ++i) {\n    printf("%d\\n", i);\n}\n','function':'int calculate(int value) {\n    return value * 2;\n}\n'}:{'for':'for (const auto& item : items) {\n    std::cout << item << "\\n";\n}\n','function':'int calculate(int value) {\n    return value * 2;\n}\n','json':'#include <cJSON.h>\n// Inside main(): cJSON *data = cJSON_CreateObject();\n'};const name=await modal('Insert a snippet','Type one of: '+Object.keys(snippets).join(', '),Object.keys(snippets)[0]);if(name&&snippets[name]){editor.replaceSelection(snippets[name]);editor.focus();}};
let pinch=null;const wrapper=editor.getWrapperElement();wrapper.addEventListener('touchstart',e=>{if(e.touches.length===2)pinch={distance:Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY),size:CBSettings.get().fontSize};},{passive:true});wrapper.addEventListener('touchmove',e=>{if(pinch&&e.touches.length===2){e.preventDefault();const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);const goal=pinch.size*distance/Math.max(pinch.distance,1);const nearest=sizes.reduce((a,b)=>Math.abs(b-goal)<Math.abs(a-goal)?b:a);if(nearest!==CBSettings.get().fontSize)CBSettings.set({fontSize:nearest});}},{passive:false});wrapper.addEventListener('touchend',()=>pinch=null,{passive:true});
})();
