/* Project library: explicit navigation, independent workspaces and source exports. */
'use strict';
(()=>{
const M=CBProjectsModel,$=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={c:'C',cpp:'C++',py:'Python'},runtimes={c:'Clang 8 · C',cpp:'Clang 8 · C++',py:'Python 3.12 · Pyodide'};
const hub=document.createElement('section');hub.id='project-hub';hub.hidden=true;hub.setAttribute('aria-label','Project management');$('academy').after(hub);
let active=false,filter='all',saved=lastProjectSaveOK;
function guard(){if(worker||mode==='native'||window.CBMemory?.isBusy()){info('Program is running','Stop the program before changing projects.');return false;}return true;}
function message(text){$('project-message').textContent=text;}
function stamp(p){return new Date(p.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function options(values,current){return values.map(([value,label])=>`<option value="${escape(value)}" ${value===current?'selected':''}>${escape(label)}</option>`).join('');}
function load(p){sync();project=p;projectLibrary.activeId=p.id;loading=true;editor.setValue(current().content);loading=false;select(p.active);}
function switchProject(id){if(!guard())return false;const p=projectLibrary.projects.find(p=>p.id===id);if(!p)return false;load(p);refresh();return true;}
function exportData(name,content){if(window.AndroidFiles)AndroidFiles.save(name,content);else if(window.Desktop)Desktop.saveFile(name,content);else browserDownload(name,content);}
function shareData(name,content){if(window.AndroidFiles?.share)AndroidFiles.share(name,content);else if(navigator.share&&navigator.canShare?.({files:[new File([content],name,{type:'application/octet-stream'})]}))navigator.share({files:[new File([content],name,{type:'application/octet-stream'})]}).catch(()=>{});else exportData(name,content);}
function starter(language){return language==='py'?'print("Hello, CodeBridge!")\n':language==='c'?'#include <stdio.h>\n\nint main(void) {\n    printf("Hello, CodeBridge!\\n");\n    return 0;\n}\n':'#include <iostream>\n\nint main() {\n    std::cout << "Hello, CodeBridge!\\n";\n    return 0;\n}\n';}
function refresh(){if(!active)return;const list=projectLibrary.projects.filter(p=>filter==='all'||p.language===filter).sort((a,b)=>b.updatedAt-a.updatedAt);const lang=names[project.language]||'Mixed';
 hub.innerHTML=`<div class="project-wrap"><div class="project-heading"><div><span class="eyebrow">CODE STUDIO</span><h1>My projects</h1><p>Create, organize, and build something yours.</p></div><span class="project-count">${projectLibrary.projects.length}</span></div>
 <div class="project-primary-actions"><button id="create-project" class="primary">＋ New project</button><button id="import-project">↥ Import</button><button id="backup-projects">↧ Backup all</button></div>
 <div class="project-filter" aria-label="Filter projects">${[['all','All'],['c','C'],['cpp','C++'],['py','Python']].map(([id,label])=>`<button data-filter="${id}" aria-pressed="${id===filter}">${label}</button>`).join('')}</div>
 <div class="project-grid">${list.map(p=>`<button class="project-card ${p.id===project.id?'selected':''}" data-project="${p.id}"><span class="project-language lang-${p.language}">${names[p.language]||'</>'}</span><span class="project-card-text"><strong>${escape(p.name)}</strong><small>${p.files.length} ${p.files.length===1?'file':'files'} · ${escape(runtimes[p.language]||'Mixed sources')}</small><small>Saved ${stamp(p)}</small></span><span class="project-arrow">${p.id===project.id?'✓':'›'}</span></button>`).join('')||'<p class="subtext">No projects in this language. Create one above.</p>'}</div>
 <section class="project-detail"><div class="project-detail-heading"><span class="project-language lang-${project.language}">${lang}</span><div><span class="eyebrow">SELECTED PROJECT</span><h2>${escape(project.name)}</h2></div><span id="project-saved" class="save-indicator ${saved?'':'save-error'}">${saved?'● Saved locally':'● Export needed'}</span></div>
 <button id="open-editor" class="primary">Open editor →</button>
 <div class="project-tools"><button id="rename-project">Rename</button><button id="duplicate-project">Duplicate</button><button id="export-selected-project">Export project</button><button id="share-selected-project">Share project</button><button id="delete-project">Delete project</button></div>
 <div class="project-section-title"><h3>Files</h3><button id="project-new-file">＋ New file</button></div>
 <div class="project-files">${project.files.map(f=>`<div class="project-file ${f.name===project.active?'selected':''}"><button data-file="${escape(f.name)}"><span class="source-mark">${/\.(h|hpp)$/.test(f.name)?'H':names[M.language(f.name)]}</span><strong>${escape(f.name)}</strong><small>${f.name===project.active?'Current file':f.name===project.entry?'Project entry':'Tap to edit'}</small></button><button data-file-export="${escape(f.name)}" aria-label="Export ${escape(f.name)}">↧</button></div>`).join('')}</div>
 <div class="project-tools"><button id="project-import-file">Import file</button><button id="project-rename-file">Rename current file</button><button id="project-delete-file">Delete current file</button><button id="project-export-file">Export source</button><button id="project-share-file">Share source</button></div>
 <h3 class="project-config-title">Build settings</h3><div class="project-config">
 <label>Compiler / runtime<select id="project-runtime">${options([[project.language,runtimes[project.language]||runtimes[M.language(project.active)]]],project.language)}</select><small>Bundled and ready offline.</small></label>
 <label>Build scope<select id="project-scope">${options([['file','Run current file'],['project','Link project sources']],project.buildScope)}</select><small>Current file runs independently. Project mode links C/C++ sources together; use one main(). Python runs the selected entry.</small></label>
 <label>Project entry<select id="project-entry">${options(project.files.filter(f=>/\.(c|cc|cpp|cxx|py)$/.test(f.name)).map(f=>[f.name,f.name]),project.entry)}</select></label>
 ${project.language!=='py'?`<label>Language standard<select id="project-standard">${options((project.language==='c'?['c99','c11','c17']:['c++11','c++14','c++17']).map(x=>[x,x.toUpperCase()]),project.compiler[project.language==='c'?'cStandard':'cppStandard'])}</select></label><label>Optimization<select id="project-optimization">${options([['O0','O0 · Easier debugging'],['O1','O1 · Balanced'],['O2','O2 · Optimized']],project.compiler.optimization)}</select></label>`:''}
 </div><p id="project-message" role="status" class="project-message">${loadedProjects.recovered?'Recovered the last readable project backup. Export a copy now.':'Your projects autosave on this device. Export a backup to keep a copy outside the app.'}</p></section></div>`;
 $('create-project').onclick=createProject;$('import-project').onclick=openFiles;$('backup-projects').onclick=()=>{sync();exportData('CodeBridge-projects.cbworkspace',JSON.stringify(projectLibrary,null,2));};
 hub.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;refresh();});hub.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>switchProject(b.dataset.project));
 $('open-editor').onclick=()=>{if(guard()){sync();CodeBridgeAcademy.navigate('code');}};
 $('rename-project').onclick=async()=>{const name=await modal('Rename project','Project name',project.name);if(name?.trim()){project.name=name.trim().slice(0,80);persist();refresh();}};
 $('duplicate-project').onclick=()=>{sync();const copy=M.normalize(JSON.parse(JSON.stringify(project)));copy.id=M.id();copy.name=(project.name+' copy').slice(0,80);projectLibrary.projects.push(copy);load(copy);filter='all';refresh();};
 $('delete-project').onclick=async()=>{if(projectLibrary.projects.length===1){await info('Keep one project','Create another project before removing this one.');return;}if(await ask('Delete project?',`Remove ${project.name} and its files from this device? Export a backup first.`)){const next=projectLibrary.projects.find(p=>p.id!==project.id);projectLibrary.projects=projectLibrary.projects.filter(p=>p.id!==project.id);project=next;loading=true;editor.setValue(current().content);loading=false;select(project.active);refresh();}};
 const snapshot=()=>{sync();return JSON.stringify(project,null,2);},projectName=()=>project.name.replace(/[^\w.-]/g,'_')+'.cbproj';$('export-selected-project').onclick=()=>exportData(projectName(),snapshot());$('share-selected-project').onclick=()=>shareData(projectName(),snapshot());
 hub.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{select(b.dataset.file);CodeBridgeAcademy.navigate('code');});hub.querySelectorAll('[data-file-export]').forEach(b=>b.onclick=()=>{sync();const f=project.files.find(f=>f.name===b.dataset.fileExport);exportData(f.name.split('/').pop(),f.content);});
 $('project-new-file').onclick=async()=>{await newFile();refresh();};$('project-import-file').onclick=openFiles;
 $('project-rename-file').onclick=async()=>{await $('rename').onclick();refresh();};$('project-delete-file').onclick=async()=>{await $('delete').onclick();refresh();};$('project-export-file').onclick=save;$('project-share-file').onclick=()=>{sync();shareData(current().name.split('/').pop(),current().content);};
 $('project-scope').onchange=e=>{project.buildScope=e.target.value;persist();};$('project-entry').onchange=e=>{project.entry=e.target.value;persist();};
 if($('project-standard'))$('project-standard').onchange=e=>{project.compiler[project.language==='c'?'cStandard':'cppStandard']=e.target.value;persist();};if($('project-optimization'))$('project-optimization').onchange=e=>{project.compiler.optimization=e.target.value;persist();};
}
const creator=document.createElement('dialog');creator.id='project-create-dialog';creator.setAttribute('aria-label','Create project');document.body.append(creator);
function createProject(){creator.innerHTML=`<form method="dialog" id="project-create-form"><div class="project-dialog-header"><h2>Start something new</h2><button value="cancel" aria-label="Cancel" formnovalidate>✕</button></div><label>Project name<input id="new-project-name" required maxlength="80" value="My project ${projectLibrary.projects.length+1}" autocomplete="off"></label><label>Language<select id="new-project-language"><option value="cpp">C++</option><option value="c">C</option><option value="py">Python</option></select></label><label>Compiler / runtime<output id="new-project-runtime">Clang 8 · C++</output></label><label>Start with<select id="new-project-template"><option value="hello">Hello world</option><option value="empty">Empty source file</option></select></label><pre id="project-template-preview" aria-label="Template preview"></pre><p id="project-create-error" role="status"></p><button value="create" class="primary">Create project</button></form>`;
 const preview=()=>{$('project-template-preview').textContent=$('new-project-template').value==='empty'?'// A blank page for your next idea':starter($('new-project-language').value);};preview();
 $('new-project-language').onchange=e=>{$('new-project-runtime').textContent=runtimes[e.target.value];preview();};$('new-project-template').onchange=preview;
 $('new-project-name').oninput=()=>{$('project-create-error').textContent=$('new-project-name').value.trim()?'':'Give your project a name.';};
 $('project-create-form').onsubmit=e=>{if(e.submitter?.value!=='create')return;const name=$('new-project-name').value.trim();if(!name||projectLibrary.projects.length>=100){e.preventDefault();$('project-create-error').textContent=!name?'Give your project a name.':'Export or remove a project before creating more.';return;}sync();const lang=$('new-project-language').value,filename='main.'+lang;const p=M.normalize({name,language:lang,files:[{name:filename,content:$('new-project-template').value==='empty'?'':starter(lang)}],active:filename});projectLibrary.projects.push(p);load(p);filter='all';refresh();};CBOverlays.open(creator,{dirtyForm:true});}

function show(){if(!guard())return;sync();CodeBridgeAcademy.navigate('projects');}
function setView(view){active=view==='projects';hub.hidden=!active;document.body.classList.toggle('project-hub-open',active);if(active){$('academy').hidden=true;refresh();}}
window.addEventListener('cb:navigate',e=>setView(e.detail.view));
window.addEventListener('cb:project-saved',()=>{saved=true;const indicator=$('project-saved');if(indicator){indicator.textContent='● Saved locally';indicator.classList.remove('save-error');}});
window.addEventListener('cb:project-save-error',()=>{saved=false;const indicator=$('project-saved');if(indicator){indicator.textContent='● Export needed';indicator.classList.add('save-error');}if($('project-message'))message('Autosave failed. Export your changes before closing the app.');});
$('editor-home').textContent='‹ Projects';$('editor-home').onclick=show;
// Everyday file actions are visible in the file panel, not buried in More actions.
const actions=document.createElement('div');actions.id='file-panel-actions';for(const [label,action] of [['New file',newFile],['Import',openFiles],['Export source',save],['Share source',()=>shareData(current().name.split('/').pop(),current().content)],['Build settings',()=>{ $('sidebar').classList.remove('visible');show();}]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;actions.append(b);}$('sidebar').insertBefore(actions,$('files'));
const saveButton=document.createElement('button');saveButton.id='editor-save';saveButton.textContent='↧';saveButton.setAttribute('aria-label','Export source file');saveButton.onclick=save;document.querySelector('header').insertBefore(saveButton,$('menu-toggle'));
const chip=document.createElement('div');chip.id='editor-project-bar';chip.innerHTML='<button id="editor-project-switch"></button><span id="editor-save-state">● Saved</span><button id="editor-file-add" aria-label="New file">＋</button>';$('tabs').before(chip);$('editor-project-switch').onclick=show;$('editor-file-add').onclick=newFile;
function updateChip(){ $('editor-project-switch').textContent=project.name+' · '+(project.buildScope==='project'?'Project build':'Current file');$('editor-save-state').textContent=saved?'● Saved':'● Export needed';$('editor-save-state').classList.toggle('save-error',!saved);}
window.addEventListener('cb:project-saved',updateChip);window.addEventListener('cb:project-save-error',updateChip);updateChip();
const nativeStatus=window.showStatus;window.showStatus=text=>{nativeStatus(text);if(active&&$('project-message'))message(text);let toast=$('project-toast');if(!toast){toast=document.createElement('div');toast.id='project-toast';toast.className='toast';toast.setAttribute('role','status');document.body.append(toast);}toast.textContent=text;toast.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>toast.hidden=true,5000);};
window.CBProjects={show,refresh,switchProject,createProject,getLibrary:()=>JSON.parse(JSON.stringify(projectLibrary)),onNativeExport:filename=>{if(active)message('Exported '+filename);},exportData};
})();
