/* Android-first learning shell. All content, progress and execution stay local. */
'use strict';
(()=>{
const P=CBProgress,courses=CBCourses,all=courses.flatMap(c=>c.lessons),ids=all.map(l=>l.id),key='codebridge.progress.v1';
let progress=P.fresh(),view='home',lessonEditor=null,lessonWorker=null,lessonTimer=null,runToken=0,toastTimer,selectedLesson=null;
try{const saved=localStorage.getItem(key);if(saved){const old=JSON.parse(saved);if(!old.economy&&!localStorage.getItem(key+'.pre-v2'))localStorage.setItem(key+'.pre-v2',saved);progress=P.validate(old,ids);}}catch{setTimeout(()=>notify('Saved learning data could not be read. Export a backup from Profile before resetting it.'),500);}
// Preserve the pre-economy save before the first migration.
try{if(!progress.economy){const old=localStorage.getItem(key);if(old&&!localStorage.getItem(key+'.pre-v2'))localStorage.setItem(key+'.pre-v2',old);}CBEconomy.init(progress);}catch{}
let committed=JSON.stringify(progress);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=document.getElementById.bind(document);
function persist(){try{const next=JSON.stringify(progress);localStorage.setItem(key,next);committed=next;return true;}catch{progress=JSON.parse(committed);notify('Storage is full. Export your progress from Profile.');return false;}}
function notify(message){let t=el('academy-toast');if(!t){t=document.createElement('div');t.id='academy-toast';t.className='toast';t.setAttribute('role','status');document.body.append(t);}t.textContent=message;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.hidden=true,4500);}
const icons={home:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7',learn:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3z M12 6v15',code:'M8 6l-6 6 6 6 M16 6l6 6-6 6 M14 3l-4 18',quests:'M8 3h8v5a4 4 0 0 1-8 0z M8 5H4v3a4 4 0 0 0 4 4 M16 5h4v3a4 4 0 0 1-4 4 M12 12v6 M8 21h8 M9 18h6',profile:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 21v-3a8 8 0 0 1 16 0v3'};
const shell=document.createElement('section');shell.id='academy';shell.setAttribute('aria-label','Learning space');el('app').insertBefore(shell,document.querySelector('.toolbar'));
const nav=document.createElement('nav');nav.className='bottom-nav';nav.setAttribute('aria-label','Main navigation');nav.innerHTML=Object.keys(icons).map(k=>`<button data-view="${k}" aria-label="${k[0].toUpperCase()+k.slice(1)}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[k]}"/></svg>${{home:'Home',learn:'Learn',code:'Code',quests:'Quests',profile:'Profile'}[k]}</button>`).join('');document.body.append(nav);
nav.onclick=e=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view);};
function cancelLesson(){runToken++;lessonWorker?.terminate();lessonWorker=null;clearTimeout(lessonTimer);lessonTimer=null;}
function navigate(next){if(view==='code'&&next!=='code'&&typeof worker!=='undefined'&&worker){notify('Stop the running program before leaving Code.');return;}cancelLesson();if(lessonEditor){lessonEditor.toTextArea();lessonEditor=null;}selectedLesson=null;view=next;document.body.classList.remove('output-mode');el('app').classList.toggle('academy-mode',next!=='code');shell.hidden=next==='code';el('menu').hidden=true;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===next;b.classList.toggle('selected',active);b.setAttribute('aria-current',active?'page':'false');});shell.scrollTop=0;if(next==='code'){requestAnimationFrame(()=>editor.refresh());return;}render();}
function title(eyebrow,heading,sub=''){return `<div class="eyebrow">${eyebrow}</div><h1 class="page-title">${heading}</h1>${sub?`<p class="subtext">${sub}</p>`:''}`;}
function count(c){return c.lessons.filter(l=>progress.completed.includes(l.id)).length;}
function courseCards(){return `<div class="course-grid">${courses.map(c=>`<button class="course-card" data-course="${c.id}"><span class="course-mark">${c.icon}</span><h3>${c.title}</h3><p>${c.subtitle}</p><div class="progress-track"><div class="progress-fill" style="width:${100*count(c)/c.lessons.length}%"></div></div><span class="small">${count(c)} / ${c.lessons.length} missions · 3 chapters</span></button>`).join('')}</div>`;}
function currentLevel(){return Math.floor(progress.xp/250)+1;}
function nextLesson(){const candidate=all.find(l=>l.id===progress.lastLesson);if(candidate&&!progress.completed.includes(candidate.id))return candidate;const course=courses.find(c=>c.lessons.some(l=>l.id===progress.lastLesson))||courses[0];return course.lessons.find(l=>!progress.completed.includes(l.id))||all.find(l=>!progress.completed.includes(l.id))||all[0];}
function stats(){return `<div class="stats-grid"><div class="stat"><strong>${progress.xp}</strong><span>TOTAL XP</span></div><div class="stat"><strong>${progress.lastActive===P.day()||progress.lastActive===P.previous()?progress.streak:0}</strong><span>DAY STREAK</span></div><div class="stat"><strong>${progress.coins}</strong><span>COINS</span></div></div>`;}
function rewardCard(){const claimed=(progress.lastReward&&progress.lastReward>=P.day())||!CBRewardClock.observe(progress);return `<div class="reward-card"><div class="reward-icon">✦</div><div><h3>Your daily discovery</h3><p>20 coins · a little reason to return</p></div><button id="daily-reward" ${claimed?'disabled':''}>${claimed?'Claimed':'Claim'}</button></div>`;}
function render(){let html='';if(view==='home'){const next=nextLesson();html=title('YOUR CODING ADVENTURE',`Hello, ${escape(progress.name)}<span style="color:var(--accent)">.</span>`,'Small steps. Real programs. A world to explore.')+stats()+`<div class="hero"><div class="orbit"></div><span class="pill">LEVEL ${currentLevel()} · ${next.stage.toUpperCase()}</span><h2>Your next breakthrough.</h2><p>${escape(next.title)} — ${escape(next.topic)}. Learn a concept, solve a puzzle, and bring your code to life.</p><button class="primary" data-lesson="${next.id}">Continue adventure →</button></div>`+rewardCard()+`<div class="section-heading"><h2>Choose your path</h2><button class="text-button" data-nav="learn">Explore all →</button></div>`+courseCards()+`<div class="section-heading"><h2>Make something yours</h2></div><div class="surface"><p class="subtext">An offline C, C++ and Python workspace, ready whenever inspiration strikes.</p><button data-nav="code" class="primary">Open code studio ↗</button></div>`;}
if(view==='learn')html=title('THE EXPEDITION','One mission at a time.','Three language paths. 39 missions from first output to recursion, algorithms, pointers, and classes.')+courseCards()+`<div class="surface" style="margin-top:20px"><span class="pill">HOW IT WORKS</span><p class="subtext" style="margin:12px 0 0">Read → answer → build → test. Finish a mission to unlock the next. Reference solutions are included, and you can replay completed missions anytime.</p></div>`;
if(view==='quests'){const daily=progress.days[P.day()]||{lessons:0,runs:0};html=title('A LITTLE EVERY DAY','Your quest board.','New goals each local calendar day. Earn XP through practice and first-time mission completions.')+stats()+rewardCard()+`<div class="section-heading"><h2>Daily quests</h2><span class="small">${P.day()}</span></div>`+[['lesson','First discovery','Complete 1 new mission',daily.lessons,1],['practice','Test pilot','Pass 2 exercise checks',daily.runs,2],['explorer','Trailblazer','Complete 3 new missions',daily.lessons,3],['memory','Memory explorer','Finish the Memory Lab exercise',daily.memory||0,1]].map(([id,name,desc,n,target])=>{const claimed=progress.claims.includes(P.day()+':'+id);return `<div class="quest-card"><div><h3>${name}</h3><span class="small">${desc} · ${Math.min(n,target)}/${target}<br>+25 XP · +15 coins</span></div><button data-claim="${id}" ${claimed||n<target?'disabled':''}>${claimed?'Claimed':'Claim'}</button></div>`;}).join('')+`<div class="section-heading"><h2>Daily challenge</h2></div>${challengeCard()}`;}
if(view==='profile'){html=title('YOUR JOURNEY',escape(progress.name),'Your learning record lives on this device. No account or connection needed.')+stats()+`<div class="surface" style="margin-top:16px"><span class="pill">LEVEL ${currentLevel()} · ${rank()}</span><div class="progress-track"><div class="progress-fill" style="width:${progress.xp%250/2.5}%"></div></div><span class="small">${250-progress.xp%250} XP to the next level · ${progress.completed.length}/${all.length} missions complete</span></div><div class="section-heading"><h2>Adventure badges</h2></div><div class="badge-grid">${[['✧','First steps',progress.completed.length>=1],['◇','Explorer',progress.completed.length>=10],['♜','Trail master',progress.completed.length>=39],...courses.map(c=>[c.icon,c.title+' path',count(c)===c.lessons.length])].map(([icon,name,on])=>`<div class="badge ${on?'earned':''}"><b>${icon}</b>${name}<div class="small">${on?'Earned':'Locked'}</div></div>`).join('')}</div><div class="profile-actions"><button id="profile-name">Edit explorer name →</button><button id="progress-export">Export progress & lesson drafts →</button><button id="progress-import">Restore progress backup →</button><button id="compatibility">Runtime compatibility & limits →</button></div><p class="small" style="margin-top:18px">Coins are collectible rewards with no cash value. Daily coins require a new local day and verified elapsed time. After a restart, unverified time is not counted. Clearing app data or uninstalling removes local progress—export a backup first.</p>`;}
shell.innerHTML='<div>'+html+'</div>';bind();}
function rank(){return progress.xp>=2000?'PATHFINDER':progress.xp>=750?'EXPLORER':'APPRENTICE';}
function dailyChallenge(){const unlocked=all.filter(l=>progress.completed.includes(l.id));const pool=unlocked.length?unlocked:[all[0]];const seed=Number(P.day().replaceAll('-',''));return pool[seed%pool.length];}
function challengeCard(){const l=dailyChallenge();return `<div class="hero"><span class="pill">PRACTICE ARENA</span><h2>${escape(l.title)}</h2><p>Today's replay mission: ${escape(l.task)} Pass the checks to advance your Test pilot quest. Replays do not award mission XP twice.</p><button class="primary" data-lesson="${l.id}">Take the challenge →</button></div>`;}
function bind(){shell.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>showCourse(b.dataset.course));shell.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));shell.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));shell.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{if(P.claim(progress,b.dataset.claim)&&persist()){window.dispatchEvent(new CustomEvent('cb:reward'));render();window.dispatchEvent(new CustomEvent('cb:celebrate'));notify('Quest complete! +25 XP and +15 coins.');}});if(el('daily-reward'))el('daily-reward').onclick=()=>{if(P.reward(progress)&&persist()){window.dispatchEvent(new CustomEvent('cb:reward'));render();window.dispatchEvent(new CustomEvent('cb:celebrate'));notify('+20 coins. Your adventure continues!');}};if(el('profile-name'))el('profile-name').onclick=async()=>{const name=await modal('Your explorer name','Choose a name (up to 24 characters).',progress.name);if(name?.trim()){progress.name=name.trim().slice(0,24);persist();render();}};if(el('progress-export'))el('progress-export').onclick=exportProgress;if(el('progress-import'))el('progress-import').onclick=importProgress;if(el('compatibility'))el('compatibility').onclick=()=>info('Offline runtime support','C11 / C++17 console programs: real Clang + libc/libc++, multiple source files, headers, standard input and output. Compiled to WebAssembly. OS-specific APIs, native GUI libraries, threads, C++ exceptions and arbitrary binary libraries are not supported.\n\nPython 3.12: bundled standard library and local Python modules. Third-party native packages, subprocesses, sockets and native GUI frameworks are not generally available.\n\nPrograms have a 30-second execution limit. Enter live input in the terminal after Run, or optionally preload it. Workspace-generated files are temporary. Python conversion covers a documented subset, not all C/C++.');}
let recentlyCompleted=null;
window.addEventListener('cb:mission',e=>{if(e.detail?.first)recentlyCompleted=e.detail.id;});
function showCourse(id){
 cancelLesson();if(lessonEditor){lessonEditor.toTextArea();lessonEditor=null;}
 const c=courses.find(c=>c.id===id);view='learn';document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view==='learn');b.setAttribute('aria-current',b.dataset.view==='learn'?'page':'false');});shell.scrollTop=0;
 const stages=[...new Set(c.lessons.map(l=>l.stage))];
 const sections=stages.map((stage,chapter)=>{
  const lessons=c.lessons.filter(l=>l.stage===stage),height=lessons.length*128+32;
  const points=lessons.map((l,i)=>({x:160+64*Math.sin(i*Math.PI/2),y:48+i*128}));
  const paths=points.slice(1).map((p,i)=>{const previous=points[i];return `<path class="path-link ${progress.completed.includes(lessons[i].id)?'mastered':''} ${recentlyCompleted===lessons[i].id?'just-completed':''}" pathLength="1" d="M${previous.x},${previous.y} C${previous.x},${previous.y+64} ${p.x},${p.y-64} ${p.x},${p.y}"/>`;}).join('');
  const nodes=lessons.map((l,i)=>{const unlocked=isUnlocked(l.id),done=progress.completed.includes(l.id),boss=l.kind==='memory_boss';const state=done?'done':unlocked?'next':'locked';return `<div class="path-stop" style="--node-x:${100*points[i].x/320}%;top:${points[i].y-30}px"><button class="level-row path-node ${state} ${recentlyCompleted===l.id?'just-completed':''} ${boss?'memory-boss':''}" data-lesson="${l.id}" ${unlocked?'':'disabled'} aria-label="${escape(l.title)} · ${done?'Mastered':unlocked?'Start':'Locked'}"><span class="level-number">${done?'✓':!unlocked?'🔒':boss?'♜':c.lessons.indexOf(l)+1}</span></button><span class="path-caption">${escape(l.title)}</span><small>${l.xp} XP</small></div>`;}).join('');
  return `<section class="path-stage"><h2 class="world-title">Chapter ${chapter+1} · ${escape(stage)}</h2><div class="journey node-map" style="height:${height}px"><svg viewBox="0 0 320 ${height}" preserveAspectRatio="none" aria-hidden="true">${paths}</svg>${nodes}</div></section>`;
 }).join('');
 shell.innerHTML='<div><button class="text-button" id="back-learn">← All paths</button>'+title(c.title+' PATH',c.title+' expedition.',c.subtitle)+`<span class="pill">${count(c)}/${c.lessons.length} MISSIONS COMPLETE</span>`+sections+'</div>';el('back-learn').onclick=()=>navigate('learn');bind();
}
function isUnlocked(id){const c=courses.find(c=>c.lessons.some(l=>l.id===id));if(!c)return false;const i=c.lessons.findIndex(l=>l.id===id);return progress.completed.includes(id)||i===0||progress.completed.includes(c.lessons[i-1].id)||c.lessons.slice(i+1).some(l=>progress.completed.includes(l.id));}
function openLesson(id){if(!isUnlocked(id)){notify('Finish the previous mission to unlock this one.');return;}cancelLesson();if(lessonEditor){lessonEditor.toTextArea();lessonEditor=null;}const l=all.find(l=>l.id===id),c=courses.find(c=>c.lessons.includes(l));selectedLesson=l;if(l.kind==='memory_boss')window.dispatchEvent(new CustomEvent('cb:memory-warning'));progress.lastLesson=id;persist();view='learn';document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view==='learn');b.setAttribute('aria-current',b.dataset.view==='learn'?'page':'false');});shell.scrollTop=0;shell.innerHTML='<div><button class="text-button" id="back-course">← '+c.title+' expedition</button>'+title(l.stage+' · '+c.title,l.title,l.topic)+`<div class="lesson-block"><h2>1. Discover</h2><p>${escape(l.explanation)}</p><details><summary>Study a worked example</summary><p>Trace each line. Then close the example and solve the exercise yourself.</p><pre>${escape(l.solution)}</pre></details></div><div class="lesson-block"><h2>2. Check your understanding</h2><p>${escape(l.question)}</p>${l.options.map((o,i)=>`<button class="answer" data-answer="${i}">${escape(o)}</button>`).join('')}<div id="quiz-feedback" class="small" role="status">${progress.quiz.includes(id)?'Concept check passed. You can answer again for practice.':'Choose one answer.'}</div></div><div class="lesson-block"><h2>3. Build it yourself</h2><p>${escape(l.task)}</p><div class="case">Sample input: ${escape(l.cases[0].input||'(none)')}<br>Expected output: ${escape(l.cases[0].output)}</div><div class="lesson-editor"><textarea id="lesson-source" aria-label="Exercise source code"></textarea></div><div class="exercise-actions"><button id="check-lesson" class="primary">▶ Check solution</button><button id="cancel-check" disabled>Stop</button><button id="reset-draft">Reset code</button></div><pre id="lesson-feedback" class="feedback" aria-live="polite">${l.cases.length} runtime check${l.cases.length>1?'s':''} · solve the quiz and pass all checks to finish.</pre><button id="next-mission" class="primary" style="margin-top:16px" hidden>Continue adventure →</button><p class="small">Checks compare output for the listed inputs. They do not prove correctness for every input or enforce the requested algorithm. Use the worked example to review your approach.</p></div></div>`;
lessonEditor=CodeMirror.fromTextArea(el('lesson-source'),{mode:c.id==='py'?'python':c.id==='c'?'text/x-csrc':'text/x-c++src',theme:'material-darker',lineNumbers:true,indentUnit:4,matchBrackets:true,autoCloseBrackets:true,lineWrapping:true,extraKeys:{Tab:cm=>cm.replaceSelection('    ')}});lessonEditor.setValue(progress.drafts[id]??l.starter);lessonEditor.on('change',()=>{progress.drafts[id]=lessonEditor.getValue();persist();});el('back-course').onclick=()=>showCourse(c.id);shell.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const correct=Number(b.dataset.answer)===l.answer;b.classList.toggle('wrong',!correct);b.classList.toggle('correct',correct);el('quiz-feedback').textContent=correct?'Correct! Now put the idea into practice.':'Not quite. Revisit the explanation and try again.';if(correct&&!progress.quiz.includes(id)){progress.quiz.push(id);persist();}});el('check-lesson').onclick=()=>checkLesson(l,c);el('cancel-check').onclick=()=>{cancelLesson();setCheckBusy(false);feedback('Stopped. Your draft is saved.');};el('reset-draft').onclick=async()=>{if(await ask('Reset this exercise?','Replace your current lesson draft with the starter code?')){cancelLesson();setCheckBusy(false);lessonEditor.setValue(l.starter);}};el('next-mission').onclick=()=>{const next=c.lessons[c.lessons.indexOf(l)+1];if(next)openLesson(next.id);else showCourse(c.id);};}
function feedback(text,kind=''){const box=el('lesson-feedback');if(box){box.textContent=text;box.className='feedback '+kind;}}
function setCheckBusy(busy){if(el('check-lesson')){el('check-lesson').disabled=busy;el('cancel-check').disabled=!busy;el('reset-draft').disabled=busy;lessonEditor?.setOption('readOnly',busy);}}
function normalize(s){return s.trim().replace(/\s+/g,' ');}
async function checkLesson(l,c){if(lessonWorker)return;if(window.CBMemory?.isBusy()){feedback('Stop Memory Lab before checking a lesson.','failure');return;}if(!progress.quiz.includes(l.id)){feedback('Answer the concept question correctly before checking your code.','failure');return;}if(typeof worker!=='undefined'&&worker){feedback('Stop your workspace program first.','failure');return;}const token=++runToken,source=l.kind==='memory_boss'?l.prefix+'\n'+lessonEditor.getValue()+'\n'+l.suffix:lessonEditor.getValue();setCheckBusy(true);window.dispatchEvent(new CustomEvent('cb:thinking'));el('next-mission').hidden=true;let index=0,trial=0,samples=[];
const runCase=()=>{if(token!==runToken)return;const test=l.cases[index];let out='',diagnostics='';feedback(`Checking ${index+1}/${l.cases.length} · trial ${trial+1}/4… Loading the offline runtime.`);lessonWorker=new Worker('engines/'+(c.id==='py'?'python-worker.js':'clang-worker.js'));const fail=text=>{lessonWorker?.terminate();lessonWorker=null;clearTimeout(lessonTimer);setCheckBusy(false);feedback(text,'failure');window.dispatchEvent(new CustomEvent('cb:lesson-error',{detail:{boss:l.kind==='memory_boss'}}));};lessonTimer=setTimeout(()=>fail('Runtime initialization timed out. Try again or restart the app.'),120000);lessonWorker.onerror=e=>fail(e.message||'Runtime could not start.');lessonWorker.onmessage=({data:m})=>{if(token!==runToken)return;if(m.event==='stdout')out+=m.text;if(m.event==='diagnostic')diagnostics=(diagnostics+m.text).slice(-6000);if(m.event==='status')feedback(`Check ${index+1}/${l.cases.length}: ${m.text}`);if(m.event==='running'){clearTimeout(lessonTimer);lessonTimer=setTimeout(()=>fail('Execution stopped after 30 seconds. Check your loop conditions.'),30000);}if(m.event==='error')fail((diagnostics+'\n'+m.text).trim());if(m.event==='done'){clearTimeout(lessonTimer);lessonWorker.terminate();lessonWorker=null;if(normalize(out)!==normalize(test.output)){fail(`Check ${index+1} needs another look.\nInput: ${test.input||'(none)'}\nExpected: ${test.output}\nReceived: ${out.trim()||'(no output)'}`);return;}if(trial>0)samples.push({case:index,ms:m.elapsedMs});trial++;if(trial<4){runCase();return;}trial=0;index++;if(index<l.cases.length){runCase();return;}P.activity(progress).runs++;const first=P.complete(progress,l);if(!persist()){setCheckBusy(false);feedback('Storage is full. Progress was not saved.','failure');return;}setCheckBusy(false);feedback(first?`Mission complete! All ${l.cases.length} checks passed.\n+${l.xp} XP · +10 coins · next mission unlocked.`:`All ${l.cases.length} checks passed. Practice recorded for today's quest.`,'success');el('next-mission').hidden=false;window.dispatchEvent(new CustomEvent('cb:mission',{detail:{id:l.id,boss:l.kind==='memory_boss',title:l.title,first,cases:l.cases.length,samples,source,language:c.id,runId:'mission-'+token,testSignature:JSON.stringify(l.cases)}}));if(first)window.dispatchEvent(new CustomEvent('cb:celebrate'));if(first)notify(`✦ ${l.title} complete! +${l.xp} XP`);}};const name='main.'+c.id;lessonWorker.postMessage({action:'run',entry:name,files:[{name,content:source}],source,stdin:test.input,breakpoints:[]});};runCase();}
function exportProgress(){const content=JSON.stringify(progress,null,2),name='CodeBridge-'+P.day()+'.cbprogress';if(window.AndroidFiles)AndroidFiles.save(name,content);else browserDownload(name,content);}
async function restore(content){try{const loaded=P.validate(JSON.parse(content),ids);if(await ask('Restore learning progress?',`Replace the current learning record with ${loaded.completed.length} completed missions and ${loaded.xp} XP? Your code workspace is unchanged.`)){progress=loaded;if(!persist())return;window.dispatchEvent(new CustomEvent('cb:economy'));navigate('profile');notify('Progress and lesson drafts restored.');}}catch(e){await info('Cannot restore backup',e.message);}}
function importProgress(){if(window.AndroidFiles)AndroidFiles.open();else{const input=document.createElement('input');input.type='file';input.accept='.cbprogress';input.onchange=async()=>{const f=input.files[0];if(f){if(f.size>8000000){notify('Backup is too large.');return;}await restore(await f.text());}};input.click();}}
const originalLoad=window.loadDocument;window.loadDocument=(name,content)=>name.endsWith('.cbprogress')?restore(content):originalLoad(name,content);
window.CodeBridgeAcademy={isChecking:()=>!!lessonWorker,navigate,openLesson,showCourse,getProgress:()=>JSON.parse(JSON.stringify(progress)),transact:operation=>{const before=progress;progress=JSON.parse(JSON.stringify(progress));try{operation(progress);CBEconomy.validate(progress);if(!persist())return false;if(!selectedLesson&&view!=='code')render();window.dispatchEvent(new CustomEvent('cb:economy'));return true;}catch(e){progress=before;notify(e.message);return false;}},restore,isUnlocked};
window.addEventListener('visibilitychange',()=>{if(!document.hidden&&['home','quests','profile'].includes(view))render();});
navigate('home');
})();
