name: codebridge_native
description: CodeBridge offline native Android compiler
publish_to: none
version: 0.8.0+8
environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  drift: 2.28.2
  sqlite3_flutter_libs: 0.5.39
  path_provider: 2.1.5
  rive: 0.13.20
  lottie: 3.3.1
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/data/
    - assets/animations/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
