'use strict';
const $=id=>document.getElementById(id);
const exampleCpp='#include <iostream>\n#include <vector>\n#include <algorithm>\n\nint main() {\n    std::vector<int> numbers = {42, 7, 19, 3};\n    std::sort(numbers.begin(), numbers.end());\n\n    std::cout << "Hello from CodeBridge!\\n";\n    for (int number : numbers) {\n        std::cout << number << " ";\n    }\n    std::cout << "\\n";\n    return 0;\n}\n';
const examplePython='def fibonacci(count):\n    values = []\n    a, b = 0, 1\n    for i in range(count):\n        values.append(a)\n        a, b = b, a + b\n    return values\n\nprint("Hello from Python!")\nprint(fibonacci(10))\n';
let project={name:'My project',active:'main.cpp',files:[{name:'main.cpp',content:exampleCpp}],breakpoints:{}};
const loadedProjects=CBProjectsModel.load(localStorage,project);
let projectLibrary=loadedProjects.state;project=projectLibrary.projects.find(p=>p.id===projectLibrary.activeId);

let executionId=0,worker=null,control=null,mode=null,timer=null,trace=[],traceCursor=0,loading=false,debugLine=null,errors=[];
const editor=CodeMirror.fromTextArea($('source'),{mode:'text/x-c++src',theme:'material-darker',lineNumbers:true,indentUnit:4,tabSize:4,matchBrackets:true,autoCloseBrackets:true,lineWrapping:false,gutters:['breakpoints','CodeMirror-linenumbers'],extraKeys:{'Ctrl-Enter':()=>execute('run'),'Cmd-Enter':()=>execute('run'),'Ctrl-S':()=>save(),'Cmd-S':()=>save(),Tab:cm=>cm.replaceSelection('    ')}});
editor.setSize('100%','100%');editor.getWrapperElement().style.fontSize=(localStorage.getItem('codebridge.font')||14)+'px';
function status(text){$('status').textContent=text;}
let lastProjectSaveOK=true;
function persist(){try{if(!project.id)project.id=CBProjectsModel.id();project.updatedAt=Date.now();const index=projectLibrary.projects.findIndex(p=>p.id===project.id);if(index<0)projectLibrary.projects.push(project);else projectLibrary.projects[index]=project;projectLibrary.activeId=project.id;CBProjectsModel.write(localStorage,projectLibrary);lastProjectSaveOK=true;window.dispatchEvent(new CustomEvent('cb:project-saved'));return true;}catch{status('Autosave failed. Export your code before closing the app.');lastProjectSaveOK=false;window.dispatchEvent(new CustomEvent('cb:project-save-error'));return false;}}

function current(){return project.files.find(f=>f.name===project.active)||project.files[0];}
function sync(){if(!loading){current().content=editor.getValue();persist();}}
editor.on('change',()=>{sync();});editor.on('cursorActivity',()=>{const p=editor.getCursor();$('cursor').textContent=`Ln ${p.line+1}, Col ${p.ch+1}`;});
editor.on('gutterClick',(_,line)=>{const list=project.breakpoints[project.active]||[];project.breakpoints[project.active]=list.includes(line+1)?list.filter(n=>n!==line+1):[...list,line+1];persist();drawBreakpoints();});
function drawBreakpoints(){editor.clearGutter('breakpoints');for(const n of project.breakpoints[project.active]||[]){const marker=document.createElement('span');marker.className='breakpoint';marker.textContent='●';editor.setGutterMarker(n-1,'breakpoints',marker);}}
function select(name){if(worker||mode==='native'){status('Stop the running program before changing files.');return;}sync();if(!project.files.some(f=>f.name===name))return;project.active=name;loading=true;editor.setValue(current().content);editor.setOption('mode',name.endsWith('.py')?'python':name.endsWith('.c')?'text/x-csrc':'text/x-c++src');loading=false;drawFiles();drawBreakpoints();persist();editor.refresh();}
function drawFiles(){for(const id of ['files','tabs']){$(id).replaceChildren();for(const file of project.files){const button=document.createElement('button');button.className=(id==='files'?'file ':'')+(file.name===project.active?'selected':'');if(id==='files'){const icon=document.createElement('span');icon.className='file-icon';icon.textContent=file.name.endsWith('.py')?'PY':file.name.endsWith('.c')?'C':'C++';button.append(icon);}button.append(document.createTextNode(file.name));button.onclick=()=>{select(file.name);$('sidebar').classList.remove('visible');};$(id).append(button);}}$('project-name').value=project.name;}
function panel(name){document.body.classList.add('output-mode');for(const el of document.querySelectorAll('.panel'))el.hidden=el.id!==name;for(const b of document.querySelectorAll('[data-panel]'))b.classList.toggle('selected',b.dataset.panel===name);}
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>panel(b.dataset.panel);
function output(text,target='output'){const el=$(target);if(el.textContent.length<220000)el.textContent+=text;el.scrollTop=el.scrollHeight;}
function activeLine(line){if(debugLine!==null)editor.removeLineClass(debugLine,'background','active-debug-line');debugLine=null;if(line){debugLine=line-1;editor.addLineClass(debugLine,'background','active-debug-line');editor.scrollIntoView({line:debugLine,ch:0},60);}}
function busy(value){for(const id of ['run','build','debug','convert'])$(id).disabled=value;$('stop').disabled=!value;editor.setOption('readOnly',value);}
function debugButtons(enabled){for(const id of ['step','next','resume','locals','stack'])$(id).disabled=!enabled;if(mode!=='native'){$('locals').disabled=true;$('stack').disabled=true;}}
function finish(message){window.CBTerminal?.end();clearTimeout(timer);timer=null;worker?.terminate();worker=null;control=null;busy(false);if(mode!=='trace')debugButtons(false);status(message);}
function stop(){window.CBFeedback?.mood('idle');if(mode==='native')window.Desktop?.debugStop();finish('Stopped');mode=null;activeLine(null);}
function onWorker(message){
 if(message.event==='input-request')CBTerminal.request();
 if(message.event==='input-resumed'){clearTimeout(timer);timer=setTimeout(()=>{stop();status('Stopped after '+CBSettings.get().timeout+' seconds.');},CBSettings.get().timeout*1000);}
 if(message.event==='status')status(message.text);
 if(message.event==='stdout')output(message.text);
 if(message.event==='diagnostic')output(message.text,'diagnostics');
 if(message.event==='compiled'){status(`Build succeeded · ${(message.bytes/1024).toFixed(1)} KB WebAssembly`);window.dispatchEvent(new CustomEvent('cb:build',{detail:{runId:executionId}}));}
 if(message.event==='running'){clearTimeout(timer);timer=setTimeout(()=>{stop();status('Stopped after '+CBSettings.get().timeout+' seconds.');},CBSettings.get().timeout*1000);}
 if(message.event==='paused'){clearTimeout(timer);activeLine(message.line);$('debug-info').textContent=`Paused at ${project.active}:${message.line}`;$('variables').textContent=Object.entries(message.vars).map(([k,v])=>`${k} = ${v}`).join('\n')+'\n\nStack\n'+message.stack.join('\n');panel('inspector');debugButtons(true);status('Paused · Step or Continue');}
 if(message.event==='done'){finish('Completed successfully');activeLine(null);window.dispatchEvent(new CustomEvent('cb:run-done'));}
 if(message.event==='error'){output(message.text+'\n','diagnostics');panel('diagnostics');finish('Stopped with errors');markDiagnostics(message.text);window.dispatchEvent(new CustomEvent('cb:code-error',{detail:{text:$('diagnostics').textContent,phase:message.phase}}));}
 if(message.event==='converted'){finish('Python conversion complete; review and test the result.');const name=project.active.replace(/\.[^.]+$/,'.py');addFileUnique(name,message.text);panel('output');$('output').textContent='Converted using the documented C/C++ subset. Review the Python before relying on it.';}
}
function markDiagnostics(){for(const line of errors)editor.removeLineClass(line,'background','compiler-error');errors=[];const text=$('diagnostics').textContent;for(const match of text.matchAll(/(?:^|\n)([^\n:]+):(\d+):\d+:\s+(?:fatal )?error/g)){if(match[1]===project.active){const line=+match[2]-1;errors.push(line);editor.addLineClass(line,'background','compiler-error');}}}
async function execute(action){
 if(window.CBMemory?.isBusy()){status('Stop Memory Lab before running your workspace.');return;}
 if(window.BitAI?.isBusy()){await info('Bit is thinking','Stop the local AI before running a program.');return;}
 if(worker||mode==='native')return;sync();const build=CBProjectsModel.request(project),python=build.entry.endsWith('.py');if(!/\.(c|cc|cpp|cxx|py)$/i.test(build.entry)){await info('Choose a source file','Select a .c, .cpp or .py file to run. Header and data files can stay in your project.');return;}
 if(action==='debug'&&!python){if(window.Desktop){await nativeDebug();return;}await info('C/C++ debugging','The offline Clang compiler supports Build and Run. Source debugging for arbitrary C/C++ is not included on Android yet. The learning trace in the menu supports simple C/C++ statements. Python has live debugging when this WebView supports shared memory.');return;}
 if(action==='build'&&python){await info('Python execution','Python runs directly. Use Run or Debug.');return;}
 if(action==='convert'&&python){status('Select a C or C++ file to convert.');return;}
 if(action==='convert'){const yes=await ask('Convert to Python','Conversion supports a limited C/C++ subset. Unsupported syntax produces an error; your source is preserved. Continue?');if(!yes)return;}
 if(action==='debug'&&typeof SharedArrayBuffer==='undefined'){await info('Debugger unavailable','This WebView does not expose shared memory. Python Run works. Update Android System WebView to try live debugging.');return;}
 $('output').textContent='';$('diagnostics').textContent='';panel('output');activeLine(null);mode=action;executionId++;busy(true);window.dispatchEvent(new CustomEvent('cb:thinking'));status('Starting…');debugButtons(false);
 const script=(python||action==='convert')?'python-worker.js':'clang-worker.js';worker=new Worker('engines/'+script);
 worker.onmessage=({data})=>onWorker(data);worker.onerror=e=>{output(e.message+'\n','diagnostics');panel('diagnostics');finish('Runtime failed');};
 control=action==='debug'?new Int32Array(new SharedArrayBuffer(4)):null;
 worker.postMessage({action,...build,stdin:$('stdin').value,...((action==='convert'||action==='build')?{}:CBTerminal.start()),breakpoints:project.breakpoints[project.active]||[],control:control?.buffer,compiler:{...CBSettings.get(),...build.compiler}});
 timer=setTimeout(()=>{stop();status('Stopped: initialization exceeded 2 minutes.');},120000);
}
async function nativeDebug(){sync();$('diagnostics').textContent='';mode='native';busy(true);panel('diagnostics');status('Starting native debugger…');try{await Desktop.debugStart({...CBProjectsModel.request(project),breakpoints:project.breakpoints[project.active]||[]});}catch(error){mode=null;finish(error.message);await info('Native debugger',error.message);}}
window.Desktop?.onDebug(message=>{if(message.event==='diagnostic')output(message.text,'diagnostics');if(message.event==='native-paused'){activeLine(message.line);debugButtons(true);panel('inspector');$('debug-info').textContent='Native debugger paused. Variables and stack appear in Build Log.';}if(message.event==='native-exit'){mode=null;finish('Native debugger exited');}if(message.event==='error'){mode=null;finish(message.text);}});
function debugCommand(command){if(mode==='native'){Desktop.debugCommand(command).catch(e=>status(e.message));if(command==='locals'||command==='stack')panel('diagnostics');return;}if(mode==='trace'){traceStep(command==='continue');return;}if(control){debugButtons(false);Atomics.store(control,0,command==='continue'?2:command==='next'?3:1);Atomics.notify(control,0);timer=setTimeout(stop,CBSettings.get().timeout*1000);}}
function traceStep(toEnd=false){if(toEnd)traceCursor=trace.length-1;const step=trace[traceCursor++];if(!step){debugButtons(false);status('Trace complete');return;}activeLine(step.line);$('variables').textContent=JSON.stringify(step.vars,null,2);$('output').textContent=step.output;$('debug-info').textContent=`Learning trace ${traceCursor}/${trace.length} · line ${step.line} (replay)`;}
async function teachingTrace(){sync();try{const result=CodeBridge.run(current().content);trace=result.trace;traceCursor=0;mode='trace';panel('inspector');debugButtons(true);traceStep();}catch(e){await info('Learning trace supports only a subset',e.message+'\nUse Run for the full bundled C/C++ compiler.');}}
function modal(title,message,value){return new Promise(resolve=>{$('modal-title').textContent=title;$('modal-message').textContent=message;$('modal-input').hidden=value===undefined;$('modal-input').value=value||'';$('modal').returnValue='';$('modal').showModal();$('modal').onclose=()=>resolve($('modal').returnValue==='ok'?(value===undefined?true:$('modal-input').value):null);if(value!==undefined)$('modal-input').focus();});}
const ask=(title,message)=>modal(title,message);const info=(title,message)=>modal(title,message);
function validate(name){return name&&name.length<180&&/^[\w. /-]+$/.test(name)&&!name.startsWith('/')&&!name.split('/').some(x=>x==='..'||!x);}
function addFileUnique(name,content){if(worker||mode==='native'){status('Stop the running program before adding files.');return;}if(project.files.length>=200){status('Maximum 200 files per project.');return;}sync();let unique=name,i=1;while(project.files.some(f=>f.name===unique))unique=name.replace(/(\.[^.]*)?$/,(_,ext)=>`_${i++}${ext||''}`);project.files.push({name:unique,content});select(unique);}
async function newFile(){const name=await modal('New file','Choose a path ending in .c, .cpp, .h or .py.','untitled.'+(project.language||CBProjectsModel.language(project.active)));if(!name)return;if(!validate(name)||! /\.(c|cc|cpp|cxx|h|hpp|py|json|txt)$/i.test(name)){await info('Choose a filename','Use a source extension such as .c, .cpp, .h or .py.');return;}addFileUnique(name,'');}
async function save(){sync();const file=current();if(window.Desktop){const ok=await Desktop.saveFile(file.name,file.content);if(ok)status('File exported');}else if(window.AndroidFiles)AndroidFiles.save(file.name.split('/').pop(),file.content);else browserDownload(file.name,file.content);}
function browserDownload(name,content){const url=URL.createObjectURL(new Blob([content],{type:/\.(cbproj|cbprogress|cbworkspace|json)$/.test(name)?'application/json':name.endsWith('.py')?'text/x-python':/\.(cpp|cc|cxx|hpp)$/.test(name)?'text/x-c++src':/\.(c|h)$/.test(name)?'text/x-csrc':'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportProject(){sync();const name=project.name.replace(/[^\w.-]/g,'_')+'.cbproj';const content=JSON.stringify(project,null,2);if(window.Desktop)await Desktop.saveFile(name,content);else if(window.AndroidFiles)AndroidFiles.save(name,content);else browserDownload(name,content);}
async function loadDocument(name,content){if(worker||mode==='native'){await info('Program is running','Stop the program before importing files.');return;}try{if(/\.cbworkspace$/i.test(name)){const imported=CBProjectsModel.validate(JSON.parse(content));if(projectLibrary.projects.length+imported.projects.length>100)throw new Error('Import would exceed 100 projects.');sync();for(const p of imported.projects){p.id=CBProjectsModel.id();projectLibrary.projects.push(p);}project=projectLibrary.projects[projectLibrary.projects.length-imported.projects.length];loading=true;editor.setValue(current().content);loading=false;select(project.active);}else if(/\.cbproj$/i.test(name)){if(projectLibrary.projects.length>=100)throw new Error('Maximum 100 projects.');sync();const p=CBProjectsModel.normalize(JSON.parse(content));p.id=CBProjectsModel.id();projectLibrary.projects.push(p);project=p;loading=true;editor.setValue(current().content);loading=false;select(project.active);}else addFileUnique(validate(name)?name:'imported.cpp',content);status('Imported '+name);window.CBProjects?.refresh();}catch(e){status('Import failed: '+e.message);await info('Could not import',e.message);}}

window.loadDocument=loadDocument;window.showStatus=status;
async function openFiles(){if(window.Desktop){const files=await Desktop.openFiles();for(const f of files||[])await loadDocument(f.name,f.content);}else if(window.AndroidFiles)AndroidFiles.open();else{const input=document.createElement('input');input.type='file';input.multiple=true;input.onchange=async()=>{for(const f of input.files)await loadDocument(f.name,await f.text());};input.click();}}
$('run').onclick=()=>execute('run');$('build').onclick=()=>execute('build');$('debug').onclick=()=>execute('debug');$('convert').onclick=()=>execute('convert');$('stop').onclick=stop;$('save').onclick=save;$('open').onclick=openFiles;$('export').onclick=exportProject;$('new-file').onclick=newFile;
$('folder').hidden=!window.Desktop;$('save-project').hidden=!window.Desktop;
$('folder').onclick=async()=>{const result=await Desktop.openFolder();if(result?.files.length){project=CBProjectsModel.normalize({name:result.name,files:result.files,active:result.files[0].name,breakpoints:{}});loading=true;editor.setValue(project.files[0].content);loading=false;select(project.active);}};
$('save-project').onclick=async()=>{sync();if(await Desktop.saveProject(project.files))status('Project saved to folder');};
$('rename').onclick=async()=>{const old=project.active,name=await modal('Rename file','Enter a new path.',old);if(name&&validate(name)&&!project.files.some(f=>f.name===name)){sync();current().name=name;if(project.entry===old)project.entry=name;project.active=name;project.breakpoints[name]=project.breakpoints[old]||[];delete project.breakpoints[old];select(name);}};
$('delete').onclick=async()=>{if(project.files.length===1){status('Keep at least one file in the project.');return;}if(await ask('Delete file','Remove '+project.active+' from this project?')){const removed=project.active;project.files=project.files.filter(f=>f.name!==removed);delete project.breakpoints[removed];project.active=project.files[0].name;if(project.entry===removed)project.entry=project.active;loading=true;editor.setValue(current().content);loading=false;select(project.active);}};
async function loadExample(name,content){if(!await ask('Load example','Open a new example workspace? Your current workspace is saved as a backup on this device.'))return;sync();localStorage.setItem('codebridge.backup',JSON.stringify(project));project=CBProjectsModel.normalize({name:'Example',active:name,files:[{name,content}],breakpoints:{}});loading=true;editor.setValue(content);loading=false;select(name);}
$('example-cpp').onclick=()=>loadExample('main.cpp',exampleCpp);$('example-python').onclick=()=>loadExample('main.py',examplePython);$('trace-c').onclick=teachingTrace;
$('step').onclick=()=>debugCommand('step');$('next').onclick=()=>debugCommand('next');$('resume').onclick=()=>debugCommand('continue');$('locals').onclick=()=>debugCommand('locals');$('stack').onclick=()=>debugCommand('stack');
$('clear').onclick=()=>{$('output').textContent='';$('diagnostics').textContent='';};$('project-name').onchange=()=>{project.name=$('project-name').value;persist();};
$('toggle-files').onclick=()=>$('sidebar').classList.toggle('visible');$('menu-toggle').onclick=()=>$('menu').hidden=!$('menu').hidden;
for(const b of $('menu').querySelectorAll('button'))b.addEventListener('click',()=>$('menu').hidden=true);
for(const b of document.querySelectorAll('[data-insert]'))b.onclick=()=>window.CBEditor.insert(b.dataset.insert);
$('font-size').onclick=async()=>{const value=await modal('Editor font','Choose a size from 10 to 24.',String(parseInt(editor.getWrapperElement().style.fontSize)||14));const n=Number(value);if(n>=10&&n<=24){editor.getWrapperElement().style.fontSize=n+'px';localStorage.setItem('codebridge.font',n);editor.refresh();}};
$('about').onclick=()=>info('CodeBridge Android 0.7','OFFLINE\nClang 8.0.1 + LLD: C11 / C++17 → WebAssembly. Standard-library console programs, project files and interactive terminal input. No OS APIs, threads or C++ exceptions.\n\nPython 3.12 via Pyodide. Live Python stepping and breakpoints when shared memory is available.\n\nDesktop native C/C++ debugging uses your installed Clang/G++ and GDB/LLDB. Android C/C++ debugging is a limited learning trace.\n\nPython conversion supports the documented subset only. General C++ conversion is not guaranteed.\n\nCode stays on your device. Open-source notices are bundled under vendor/.');
loading=true;editor.setValue(current().content);loading=false;select(project.active);window.addEventListener('resize',()=>editor.refresh());

window.addEventListener('pagehide',sync);document.addEventListener('visibilitychange',()=>{if(document.hidden)sync();});
