'use strict';
(()=>{
const $=document.getElementById.bind(document);let audioContext,fxTimer;
function allEditors(){return [...document.querySelectorAll('.CodeMirror')].map(el=>el.CodeMirror).filter(Boolean);}
function apply(){const s=CBSettings.get(),root=document.documentElement;root.dataset.theme=s.theme;root.dataset.editorTheme=s.editorTheme;root.dataset.motion=s.motion?'on':'off';for(const cm of allEditors()){cm.setOption('lineWrapping',s.wrap);cm.setOption('lineNumbers',s.lineNumbers);cm.setOption('indentUnit',s.indent);cm.setOption('tabSize',s.indent);cm.setOption('autoCloseBrackets',s.closeBrackets);cm.setOption('extraKeys',{...cm.getOption('extraKeys'),Tab:cm=>cm.replaceSelection(' '.repeat(CBSettings.get().indent))});cm.getWrapperElement().style.fontSize=s.fontSize+'px';cm.refresh();}}
function sound(){if(!CBSettings.get().sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const t=audioContext.currentTime;[523.25,659.25,783.99].forEach((freq,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,t+i*.09);gain.gain.linearRampToValueAtTime(.07,t+i*.09+.02);gain.gain.exponentialRampToValueAtTime(.001,t+i*.09+.24);osc.connect(gain).connect(audioContext.destination);osc.start(t+i*.09);osc.stop(t+i*.09+.25);});}catch{}}
document.addEventListener('pointerdown',()=>{if(CBSettings.get().sound){try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}}},{passive:true});
function celebrate(){sound();if(!CBSettings.get().motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;$('celebration')?.remove();clearTimeout(fxTimer);const fx=document.createElement('div');fx.id='celebration';fx.className='celebration';fx.setAttribute('aria-hidden','true');for(let i=0;i<24;i++){const p=document.createElement('i'),angle=i*Math.PI*2/24;p.style.setProperty('--x',Math.cos(angle)*(80+Math.random()*150)+'px');p.style.setProperty('--y',Math.sin(angle)*180+150+'px');p.style.setProperty('--r',(i*51)+'deg');fx.append(p);}document.body.append(fx);fxTimer=setTimeout(()=>fx.remove(),1000);}
const mascot=`<svg class="bit-mascot" viewBox="0 0 100 100" role="img" aria-label="Bit, your coding companion"><path class="antenna" d="M50 25V12"/><circle class="body" cx="50" cy="10" r="5"/><rect class="feet" x="23" y="74" width="18" height="12" rx="5"/><rect class="feet" x="59" y="74" width="18" height="12" rx="5"/><rect class="body" x="13" y="24" width="74" height="54" rx="22"/><rect class="visor" x="23" y="35" width="54" height="30" rx="13"/><rect class="eye" x="33" y="44" width="8" height="11" rx="4"/><rect class="eye" x="59" y="44" width="8" height="11" rx="4"/><path d="M45 58q5 4 10 0" stroke="currentColor" fill="none" stroke-width="2"/></svg>`;
function decorate(){const host=$('academy');if(!host)return;const hero=host.querySelector('.hero');if(hero&&!host.querySelector('.mascot-welcome')){const card=document.createElement('div');card.className='mascot-welcome';card.innerHTML=mascot+'<p><strong>Meet Bit. Your coding companion.</strong>Every great program starts with one small idea. Let’s build yours.</p>';hero.before(card);}apply();}
const heading=document.createElement('div');heading.className='console-heading';heading.innerHTML='<button id="back-editor">← Editor</button><div><strong>Program console</strong><small>Output, input and debugging</small></div><span class="spacer"></span>';$('console').prepend(heading);$('back-editor').onclick=()=>{document.body.classList.remove('output-mode');editor.refresh();editor.focus();};
const open=document.createElement('button');open.id='console-open';open.textContent='Console';open.onclick=()=>panel('output');document.querySelector('.toolbar').append(open);
const input=document.createElement('button');input.id='input-open';input.textContent='Input';input.onclick=()=>panel('input');document.querySelector('.toolbar').insertBefore(input,$('build'));document.querySelector('.toolbar').insertBefore(open,$('build'));$('run').after($('stop'));
try{$('stdin').value=localStorage.getItem('codebridge.stdin')||'';}catch{}$('stdin').addEventListener('input',()=>{try{localStorage.setItem('codebridge.stdin',$('stdin').value);}catch{status('Input could not be saved: device storage is full.');}});
const settingsButton=document.createElement('button');settingsButton.id='settings-open';settingsButton.setAttribute('aria-label','Settings');settingsButton.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2" fill="var(--surface)"/><circle cx="16" cy="12" r="2" fill="var(--surface)"/><circle cx="10" cy="18" r="2" fill="var(--surface)"/></svg>';document.querySelector('header').append(settingsButton);
const dialog=document.createElement('dialog');dialog.id='settings-dialog';dialog.setAttribute('aria-label','Settings');document.body.append(dialog);
const choices={theme:[['midnight','Midnight','#141824'],['forest','Forest','#163b2d'],['violet','Violet','#3e2854'],['paper','Paper','#e9edda']],editorTheme:[['night','Night','#10131c'],['ocean','Ocean','#10304a'],['plum','Plum','#392145'],['day','Day','#faf9f0']]};
function swatches(key){const value=CBSettings.get()[key];return '<div class="theme-options">'+choices[key].map(([id,name,color])=>`<button data-setting="${key}" data-value="${id}" aria-pressed="${id===value}"><i style="--swatch:${color}"></i>${name}</button>`).join('')+'</div>';}
function select(key,label,options,help=''){const value=CBSettings.get()[key];return `<label class="setting-row"><span>${label}${help?'<small>'+help+'</small>':''}</span><select data-setting="${key}" aria-label="${label}">${options.map(n=>`<option value="${n}" ${n===value?'selected':''}>${n}</option>`).join('')}</select></label>`;}
function toggle(key,label,help=''){return `<label class="setting-row"><span>${label}${help?'<small>'+help+'</small>':''}</span><input type="checkbox" data-setting="${key}" ${CBSettings.get()[key]?'checked':''}></label>`;}
function showSettings(){dialog.innerHTML='<div class="settings-header"><h2>Make it yours.</h2><button id="settings-close" aria-label="Close settings">✕</button></div><div id="settings-content"><div class="settings-section"><h3>App appearance</h3>'+swatches('theme')+'</div><div class="settings-section"><h3>Editor palette</h3>'+swatches('editorTheme')+'<div class="settings-preview"><b>print</b>(<em>"Hello, explorer!"</em>)<br>// Your next idea starts here.</div></div><div class="settings-section"><h3>Your coding space</h3>'+select('fontSize','Font size',[11,12,13,14,15,16,18,20,22,24])+select('indent','Indent spaces',[2,4,8])+toggle('suggestions','Code suggestions','Keywords and names from your current file.')+toggle('wrap','Wrap long lines')+toggle('lineNumbers','Line numbers')+toggle('closeBrackets','Close brackets automatically')+select('cStandard','C standard',['c99','c11','c17'])+select('cppStandard','C++ standard',['c++11','c++14','c++17'])+select('optimization','Optimization',['O0','O1','O2'])+select('timeout','Run limit (seconds)',[30,60,120],'Workspace only. Lesson checks allow 30 seconds.')+'</div><div class="settings-section"><h3>Sound & motion</h3>'+toggle('sound','Reward sounds','Soft synthesized notes. Off by default.')+toggle('motion','Animations & celebrations','Also respects your device’s reduced-motion preference.')+toggle('roast','Roman Urdu roast mode','Preset jokes about broken code. Off by default.')+'<button id="sound-preview" style="margin-top:12px">Preview reward sound</button></div><p class="small" style="margin-top:20px">Settings save automatically on this device. Code and lesson drafts keep autosaving. Android 0.6 · offline by design.</p><button id="reset-settings">Reset settings to defaults</button></div>';
$('settings-close').onclick=()=>dialog.close();dialog.querySelectorAll('button[data-setting]').forEach(b=>b.onclick=()=>{CBSettings.set({[b.dataset.setting]:b.dataset.value});for(const sibling of b.parentElement.children)sibling.setAttribute('aria-pressed',sibling===b?'true':'false');});dialog.querySelectorAll('select[data-setting],input[data-setting]').forEach(control=>control.onchange=()=>CBSettings.set({[control.dataset.setting]:control.type==='checkbox'?control.checked:(Number.isNaN(Number(control.value))?control.value:Number(control.value))}));$('sound-preview').onclick=()=>{if(CBSettings.get().sound)sound();else $('sound-preview').textContent='Enable Reward sounds above to preview';};$('reset-settings').onclick=()=>{CBSettings.set(CBSettings.defaults);showSettings();};if(!dialog.open)dialog.showModal();}
settingsButton.onclick=showSettings;$('font-size').onclick=showSettings;
window.addEventListener('cb:settings',apply);window.addEventListener('cb:celebrate',celebrate);window.addEventListener('cb:storage-error',()=>status('Settings could not be saved. Device storage is full.'));
// Observe only view replacement, avoiding mutations caused by editor refresh.
new MutationObserver(decorate).observe($('academy'),{childList:true});decorate();
let fullHeight=window.innerHeight;function keyboard(){fullHeight=Math.max(fullHeight,window.innerHeight);const height=window.visualViewport?.height||window.innerHeight;const typing=/^(TEXTAREA|INPUT)$/.test(document.activeElement?.tagName||'');document.body.classList.toggle('keyboard-open',typing&&height<fullHeight*.78);}
window.visualViewport?.addEventListener('resize',keyboard);window.addEventListener('resize',keyboard);document.addEventListener('focusout',()=>setTimeout(keyboard,80));
window.CBExperience={showSettings,celebrate,apply};
window.codebridgeBack=()=>{if(dialog.open){dialog.close();return true;}if($('modal').open){$('modal').close();return true;}if(document.body.classList.contains('output-mode')){$('back-editor').click();return true;}if(document.querySelector('[data-view=home]')?.getAttribute('aria-current')!=='page'){CodeBridgeAcademy.navigate('home');return true;}return false;};
})();
