# Generated by CodeBridge. Review behavior before relying on the result.
def c_div(a, b):
    return int(a / b) if isinstance(a, int) and isinstance(b, int) else a / b

def main():
    a = 7
    b = 2
    print("Result: ", c_div(a, b), sep="", end="")
    print()
    return 0

if __name__ == "__main__":
    main()
