# Generated by CodeBridge. Review behavior before relying on the result.
def main():
    total = 0
    i = 0
    while (i < 5):
        total += i
        i += 1
    print('Total: {}\n'.format(total), end="")
    return 0

if __name__ == "__main__":
    main()
