/* One overlay lifecycle for dialogs, menus, drawers, selections and editor popovers. */
'use strict';
(()=>{
const nativeOpen=HTMLDialogElement.prototype.showModal,nativeClose=HTMLDialogElement.prototype.close;
const stack=[],records=new WeakMap();let syncing=false,pendingConfirm=false;
const focusables=n=>[...n.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex]:not([tabindex="-1"])')].filter(e=>!e.hidden&&e.getClientRects().length);
const visible=n=>n.isConnected&&(n instanceof HTMLDialogElement?n.open:n.id==='sidebar'?n.classList.contains('visible'):!n.hidden&&getComputedStyle(n).display!=='none');
function lock(){document.body.classList.toggle('overlay-locked',stack.length>0);document.body.dataset.overlayDepth=stack.length;}
function register(node,options={}){let r=records.get(node);if(!r){r={node,options,trigger:null};records.set(node,r);node.dataset.overlay='';if(node instanceof HTMLDialogElement){node.addEventListener('close',()=>removed(r));node.addEventListener('cancel',e=>{e.preventDefault();dismiss(node,'escape');});}node.addEventListener('pointerdown',e=>{r.drag={x:e.clientX,y:e.clientY,scroll:node.scrollTop,target:e.target};if(!e.target.closest('input,textarea,select,.CodeMirror,button'))try{node.setPointerCapture(e.pointerId);}catch{}});node.addEventListener('pointerup',e=>{const d=r.drag;r.drag=null;if(d&&d.scroll===0&&!d.target.closest('input,textarea,select,.CodeMirror,button')&&e.clientY-d.y>90&&Math.abs(e.clientX-d.x)<60)dismiss(node,'swipe');});}r.options={...r.options,...options};return r;}
function formSnapshot(n){return JSON.stringify([...n.querySelectorAll('input,textarea,select')].map(e=>[e.name||e.id,e.type==='checkbox'?e.checked:e.value]));}
function added(r){if(stack.includes(r))return;r.trigger??=document.activeElement;r.baseline=formSnapshot(r.node);stack.push(r);lock();r.node.setAttribute('aria-modal',r.options.kind==='suggestion'?'false':'true');if(!(r.node instanceof HTMLDialogElement)){r.node.setAttribute('role',r.options.kind==='suggestion'?'listbox':'dialog');if(r.options.kind!=='suggestion')queueMicrotask(()=>focusables(r.node)[0]?.focus({preventScroll:true}));}}
function removed(r){const index=stack.indexOf(r);if(index<0)return;const top=index===stack.length-1;stack.splice(index,1);lock();r.options.onClose?.();if(top&&r.trigger?.isConnected&&(!stack.length||stack.at(-1).node.contains(r.trigger)))r.trigger.focus({preventScroll:true});}
function open(node,options={}){if(typeof node==='string')node=document.getElementById(node);const r=register(node,options);if(!stack.includes(r))r.trigger=document.activeElement;if(node instanceof HTMLDialogElement){if(!node.open)nativeOpen.call(node);}else if(node.id==='sidebar')node.classList.add('visible');else node.hidden=false;added(r);return node;}
function close(node,value=''){if(typeof node==='string')node=document.getElementById(node);if(!node)return;const r=records.get(node);if(node instanceof HTMLDialogElement){if(node.open)nativeClose.call(node,value);}else if(node.id==='sidebar')node.classList.remove('visible');else if(node.matches('.CodeMirror-hints')){r?.options.onDismiss?.();if(node.isConnected)node.remove();}else if(node.matches('.CodeMirror-dialog')){r?.options.onDismiss?.();node.remove();}else node.hidden=true;if(r)removed(r);}
async function confirmDiscard(){if(pendingConfirm)return false;pendingConfirm=true;const d=document.createElement('dialog');d.id='overlay-discard';d.setAttribute('aria-label','Discard unsaved edits');d.innerHTML='<h2>Keep your changes?</h2><p>These edits have not been saved.</p><div class="dialog-actions"><button data-keep>Keep editing</button><button data-discard>Discard edits</button></div>';document.body.append(d);open(d);return new Promise(resolve=>{let answer=false;d.querySelector('[data-keep]').onclick=()=>close(d);d.querySelector('[data-discard]').onclick=()=>{answer=true;close(d);};d.addEventListener('close',()=>{pendingConfirm=false;d.remove();resolve(answer);},{once:true});});}
async function dismiss(node,reason='outside'){const r=records.get(node);if(!r)return false;if(r.dismissing)return true;r.dismissing=true;try{const dirty=r.options.dirty?.()??(r.options.dirtyForm&&formSnapshot(node)!==r.baseline);if(dirty&&!await confirmDiscard())return true;close(node);return true;}finally{r.dismissing=false;}}
function back(){const r=stack.at(-1);if(!r)return false;dismiss(r.node,'back');return true;}
function toggle(node,options={}){if(typeof node==='string')node=document.getElementById(node);if(visible(node))dismiss(node,'toggle');else open(node,options);}
HTMLDialogElement.prototype.showModal=function(){open(this);};HTMLDialogElement.prototype.close=function(value){close(this,value);};
document.addEventListener('pointerdown',e=>{const r=stack.at(-1);if(!r||r.node.contains(e.target)&&e.target!==r.node||r.trigger?.contains(e.target))return;const b=r.node.getBoundingClientRect();if(e.target===r.node&&e.clientX>=b.left&&e.clientX<=b.right&&e.clientY>=b.top&&e.clientY<=b.bottom)return;dismiss(r.node,'outside');},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-overlay-close]');if(b){e.preventDefault();dismiss(b.closest('[data-overlay]')||stack.at(-1)?.node,'button');}},true);
document.addEventListener('submit',e=>{const d=e.target.closest('dialog');if(d&&e.submitter?.value==='cancel'){e.preventDefault();dismiss(d,'cancel');}},true);
document.addEventListener('keydown',e=>{const r=stack.at(-1);if(!r)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();dismiss(r.node,'escape');return;}if(e.key==='Tab'&&r.options.kind!=='suggestion'){const f=focusables(r.node);if(!f.length){e.preventDefault();return;}const i=f.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();f.at(-1).focus();}else if(!e.shiftKey&&(i<0||i===f.length-1)){e.preventDefault();f[0].focus();}}},true);
function scan(){if(syncing)return;syncing=true;for(const node of document.querySelectorAll('dialog,#menu,#execution-tools,#sidebar,.CodeMirror-hints,.CodeMirror-dialog')){const r=register(node,{kind:node.matches('.CodeMirror-hints')?'suggestion':undefined});if(visible(node))added(r);else removed(r);}for(const r of [...stack])if(!r.node.isConnected)removed(r);syncing=false;}
new MutationObserver(scan).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden','open','class']});
// App-owned dropdowns use the same selection sheet. Native file/share pickers remain OS-owned.
let selectSheet;
function choose(select){if(select.disabled)return;selectSheet??=document.body.appendChild(document.createElement('dialog'));selectSheet.id='overlay-select';selectSheet.setAttribute('aria-label',select.closest('label')?.childNodes[0]?.textContent.trim()||select.getAttribute('aria-label')||'Choose an option');selectSheet.replaceChildren();const title=document.createElement('h2');title.textContent=selectSheet.getAttribute('aria-label');selectSheet.append(title);for(const option of select.options){const button=document.createElement('button');button.type='button';button.className='overlay-option';button.disabled=option.disabled;button.textContent=(option.value===select.value?'✓ ':'')+option.text;button.onclick=()=>{select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));close(selectSheet);select.focus({preventScroll:true});};selectSheet.append(button);}open(selectSheet);}
document.addEventListener('pointerdown',e=>{if(e.target instanceof HTMLSelectElement){e.preventDefault();choose(e.target);}},true);document.addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement&&['Enter',' ','ArrowDown'].includes(e.key)&&!e.ctrlKey){e.preventDefault();choose(e.target);}},true);
window.CBOverlays={open,close,dismiss,toggle,register,back,depth:()=>stack.length,top:()=>stack.at(-1)?.node,scan};
document.addEventListener('DOMContentLoaded',()=>{scan();window.codebridgeBack=()=>{if(back())return true;if(document.body.classList.contains('output-mode')){document.getElementById('back-editor').click();return true;}if(document.body.classList.contains('focus-editor')){document.body.classList.remove('focus-editor');return true;}if(!document.getElementById('app').classList.contains('academy-mode')){window.CBProjects?.show();return true;}if(document.querySelector('[data-view=home]')?.getAttribute('aria-current')!=='page'){CodeBridgeAcademy.navigate('home');return true;}return false;};});
})();
