(function(root){'use strict';
const catalog=[
{id:'palette-neon',name:'Neon Circuit',category:'editor_palette',priceCoins:60,assetKey:'neon'},
{id:'palette-ember',name:'Ember',category:'editor_palette',priceCoins:60,assetKey:'ember'},
{id:'border-circuit',name:'Circuit frame',category:'ui_border',priceCoins:100,assetKey:'circuit'},
{id:'skin-ice',name:'Glacier Bit',category:'bit_skin',priceCoins:180,assetKey:'bit-ice'},
{id:'skin-sunset',name:'Sunset Bit',category:'bit_skin',priceCoins:180,assetKey:'bit-sunset'},
{id:'palette-default',name:'Settings palette',category:'editor_palette',priceCoins:0,assetKey:'default'},
{id:'border-default',name:'Clean frame',category:'ui_border',priceCoins:0,assetKey:'default'},
{id:'skin-default',name:'Original Bit',category:'bit_skin',priceCoins:0,assetKey:'bit-lime'}];
const slots={editor_palette:'editorPalette',bit_skin:'bitSkin',ui_border:'uiBorder'};
function init(p){if(p.economy)return p.economy;p.economy={revision:0,ownedItemIds:['palette-default','border-default','skin-default'],equipped:{editorPalette:'palette-default',bitSkin:'skin-default',uiBorder:'border-default'},transactions:[{id:'migration-v2',idempotencyKey:'migration-v2',kind:'migration',sourceId:'legacy',coinsDelta:p.coins,xpDelta:p.xp,createdAt:new Date().toISOString()}]};for(const key of p.claims||[])p.economy.transactions.push({id:'legacy-claim-'+p.economy.transactions.length,idempotencyKey:'quest:'+key,kind:'migration',sourceId:key.split(':').pop(),coinsDelta:0,xpDelta:0,createdAt:new Date().toISOString()});if(p.lastReward)p.economy.transactions.push({id:'legacy-daily',idempotencyKey:'daily:'+p.lastReward,kind:'migration',sourceId:'daily-discovery',coinsDelta:0,xpDelta:0,createdAt:new Date().toISOString()});p.economy.revision=p.economy.transactions.length;return p.economy;}
function credit(p,key,coins,xp,sourceId){const e=init(p);if(e.transactions.some(t=>t.idempotencyKey===key))return false;e.transactions.push({id:'tx-'+e.revision,idempotencyKey:key,kind:'reward',sourceId,coinsDelta:coins,xpDelta:xp,createdAt:new Date().toISOString()});e.revision++;p.coins+=coins;p.xp+=xp;return true;}
function buy(p,id){const item=catalog.find(i=>i.id===id);if(!item)throw Error('Unknown item');const e=init(p);if(e.ownedItemIds.includes(id))return false;if(p.coins<item.priceCoins)throw Error('Not enough coins yet. Complete missions or daily quests.');e.transactions.push({id:'tx-'+e.revision,idempotencyKey:'purchase:'+id,kind:'purchase',sourceId:id,coinsDelta:-item.priceCoins,xpDelta:0,createdAt:new Date().toISOString()});e.revision++;p.coins-=item.priceCoins;e.ownedItemIds.push(id);return true;}
function equip(p,id){const e=init(p),item=catalog.find(i=>i.id===id);if(!item||!e.ownedItemIds.includes(id))throw Error('Unlock this cosmetic first.');e.equipped[slots[item.category]]=id;e.revision++;}
function validate(p){const e=init(p);if(!e||!Number.isSafeInteger(e.revision)||e.revision<0||!Array.isArray(e.transactions)||!Array.isArray(e.ownedItemIds)||!e.equipped)throw Error('Invalid economy save');if(new Set(e.ownedItemIds).size!==e.ownedItemIds.length||e.ownedItemIds.some(id=>!catalog.some(i=>i.id===id)))throw Error('Invalid ownership');let coins=0,xp=0;const keys=new Set(),txIds=new Set();for(const t of e.transactions){if(!t||typeof t.id!=='string'||txIds.has(t.id)||typeof t.idempotencyKey!=='string'||keys.has(t.idempotencyKey)||!Number.isSafeInteger(t.coinsDelta)||!Number.isSafeInteger(t.xpDelta)||t.xpDelta<0||!['reward','purchase','migration'].includes(t.kind)||!Number.isFinite(Date.parse(t.createdAt)))throw Error('Invalid transaction history');keys.add(t.idempotencyKey);txIds.add(t.id);if(t.kind==='purchase'){const item=catalog.find(i=>i.id===t.sourceId);if(!item||t.coinsDelta!==-item.priceCoins||t.xpDelta!==0||!e.ownedItemIds.includes(item.id))throw Error('Invalid purchase');}else if(t.coinsDelta<0)throw Error('Invalid reward');coins+=t.coinsDelta;xp+=t.xpDelta;if(coins<0)throw Error('Invalid balance');}if(coins!==p.coins||xp!==p.xp)throw Error('Economy totals do not match transaction history');for(const [category,slot]of Object.entries(slots)){const item=catalog.find(i=>i.id===e.equipped[slot]);if(!item||item.category!==category||!e.ownedItemIds.includes(item.id))throw Error('Invalid equipped cosmetic');}for(const id of e.ownedItemIds){const item=catalog.find(i=>i.id===id);if(item.priceCoins&&!keys.has('purchase:'+id))throw Error('Missing purchase record');}return e;}
function snapshot(p){
 const e=init(p),date=new Date(),today=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,stats=p.days[today]||{};
 const definitions=[['daily-discovery','Daily discovery','daily_discovery_claim',1,20,0],['lesson','First discovery','first_missions_passed',1,15,25],['practice','Test pilot','successful_exercise_checks',2,15,25],['explorer','Trailblazer','first_missions_passed',3,15,25],['memory','Memory explorer','memory_exercise_passed',1,15,25]];
 const quests=definitions.map(([id,title,metric,target,coins,xp])=>({id,title,cadence:'daily',objective:{metric,target},reward:{coins,xp},prerequisites:[]}));
 const questProgress=quests.map(q=>{const daily=q.id==='daily-discovery',key=daily?'daily:'+today:'quest:'+today+':'+q.id,t=e.transactions.find(t=>t.idempotencyKey===key),claimed=daily?p.lastReward===today:p.claims.includes(today+':'+q.id);const value=daily?(p.lastReward===today?1:0):q.id==='practice'?(stats.runs||0):q.id==='memory'?(stats.memory||0):(stats.lessons||0);const result={questId:q.id,periodKey:today,value,evidenceIds:[],claimed:!!t};if(t)result.claimTransactionId=t.id;return result;});
 return {schemaVersion:2,contentVersion:'0.7',quests,catalog,player:{...e,coins:p.coins,xp:p.xp,questProgress}};
}
const api={snapshot,catalog,slots,init,credit,buy,equip,validate};if(typeof module!=='undefined')module.exports=api;else root.CBEconomy=api;
})(globalThis);
