'use strict';
(()=>{
const reduced=()=>!CBSettings.get().motion||matchMedia('(prefers-reduced-motion: reduce)').matches;
let context,decoded={},active=0;const unlocked=()=>{if(!CBSettings.get().sound)return;context??=new (window.AudioContext||window.webkitAudioContext)();context.resume().catch(()=>{});};document.addEventListener('pointerdown',unlocked,{passive:true});
async function sound(name){if(!CBSettings.get().sound)return;try{unlocked();if(!context||context.state!=='running'||active>=2)return;if(!decoded[name])decoded[name]=fetch('game/assets/'+name+'.wav').then(r=>r.arrayBuffer()).then(b=>context.decodeAudioData(b));const data=await decoded[name];if(!CBSettings.get().sound||document.hidden||active>=2)return;const source=context.createBufferSource();source.buffer=data;source.connect(context.destination);active++;source.onended=()=>active--;source.start();}catch{}}

const names=['idle','wave','cheer','celebrate','think','confused','oops','encouraging','sleepy','level-up','boss-fight'];
let state='idle',timer=0,queue=[],serial=0;const low=(navigator.hardwareConcurrency||2)<=2||(navigator.deviceMemory||2)<=2;
function svg(){const id='bit-'+(++serial);return `<svg viewBox="0 0 120 120" class="bit-rig" aria-hidden="true"><defs><linearGradient id="${id}" x2=".3" y2="1"><stop stop-color="#d4ff9d"/><stop offset=".65" stop-color="var(--bit-body,#9dea58)"/><stop offset="1" stop-color="#418838"/></linearGradient><radialGradient id="${id}-eye"><stop stop-color="#314055"/><stop offset="1" stop-color="#101d2d"/></radialGradient></defs><ellipse cx="60" cy="109" rx="30" ry="5" fill="#071521" opacity=".18"/><g class="bit-body"><g class="bit-feet" fill="#317c45"><ellipse cx="43" cy="99" rx="13" ry="8"/><ellipse cx="77" cy="99" rx="13" ry="8"/></g><path class="bit-arm bit-left" d="M30 60 Q9 62 17 81 Q25 90 33 74" fill="url(#${id})"/><path class="bit-arm bit-right" d="M90 60 Q111 62 103 81 Q95 90 87 74" fill="url(#${id})"/><path d="M59 24 Q47 10 59 8 Q70 10 62 24" fill="#a4f36c"/><path d="M25 53 Q24 26 60 25 Q96 26 95 53 L93 79 Q90 100 60 101 Q30 100 27 79Z" fill="url(#${id})" stroke="#d6ffb0" stroke-width="2"/><path d="M34 45 Q45 30 66 32" fill="none" stroke="#efffdb" stroke-width="5" stroke-linecap="round" opacity=".7"/><g class="bit-eyes"><ellipse cx="45" cy="60" rx="12" ry="16" fill="#f8ffed"/><ellipse cx="75" cy="60" rx="12" ry="16" fill="#f8ffed"/><g class="bit-pupils"><ellipse cx="47" cy="61" rx="6" ry="9" fill="url(#${id}-eye)"/><ellipse cx="73" cy="61" rx="6" ry="9" fill="url(#${id}-eye)"/><circle cx="49" cy="57" r="2" fill="white"/><circle cx="75" cy="57" r="2" fill="white"/></g></g><path d="M49 83 Q60 93 71 83" fill="none" stroke="#234c32" stroke-width="4" stroke-linecap="round"/><ellipse cx="34" cy="78" rx="6" ry="3" fill="#f0b6a4" opacity=".5"/><ellipse cx="86" cy="78" rx="6" ry="3" fill="#f0b6a4" opacity=".5"/></g></svg>`;}
function skin(node,key){node.dataset.skin=key||CBEconomy.catalog.find(x=>x.id===CodeBridgeAcademy.getProgress().economy?.equipped.bitSkin)?.assetKey||'bit-lime';}
function apply(){for(const n of document.querySelectorAll('.bit-stage')){n.dataset.state=state;n.dataset.still=String(reduced());n.setAttribute('aria-label','Bit: '+state);}}
function play(next,options={}){if(!names.includes(next))throw Error('Unknown Bit animation');if(options.queue&&state!=='idle'){if(queue.length<8)queue.push([next,options]);return;}clearTimeout(timer);if(!options.queue)queue=[];state=next;apply();window.dispatchEvent(new CustomEvent('cb:bit',{detail:{state}}));if(next!=='idle')timer=setTimeout(()=>{const pending=queue.shift();if(pending)play(pending[0],{...pending[1],queue:false});else{state='idle';apply();}},options.duration||1400);}
const phrases={cheer:'You did it!',celebrate:'Another step forward!',think:'One small step at a time.',confused:'Let’s look at that together.',oops:'Mistakes are part of learning.',encouraging:'Try one more idea.',sleepy:'A little rest helps.', 'level-up':'A new level!', 'boss-fight':'You’ve got this!'};
function speak(text){for(const n of document.querySelectorAll('.mascot-welcome')){let b=n.querySelector('.bit-bubble');if(!b){b=document.createElement('span');b.className='bit-bubble';b.setAttribute('role','status');n.append(b);}b.textContent=text;clearTimeout(b._timer);b._timer=setTimeout(()=>b.remove(),3500);}}
function mount(){for(const old of document.querySelectorAll('.bit-mascot,.store-sprite:not([data-rig])')){if(old.classList.contains('store-sprite')){old.dataset.rig='true';old.style.backgroundImage='none';old.innerHTML=svg();skin(old,old.dataset.skin);continue;}const stage=document.createElement('div');stage.className='bit-stage';stage.tabIndex=0;stage.setAttribute('role','button');stage.innerHTML='<div class="bit-sprite">'+svg()+'</div>';old.replaceWith(stage);skin(stage);stage.onclick=()=>{play('wave');speak('Hello, coder!');};stage.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();stage.click();}};}apply();}
let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;if(document.querySelector('.bit-mascot,.store-sprite:not([data-rig])'))mount();});}).observe(document.getElementById('academy'),{childList:true,subtree:true});mount();
const layer=document.createElement('div');layer.id='game-particles';layer.setAttribute('aria-hidden','true');document.body.append(layer);
function burst(count=12,type='confetti'){if(reduced()||document.hidden)return;const rect=document.getElementById('run').getBoundingClientRect(),x=rect.width?rect.x+rect.width/2:innerWidth/2,y=rect.width?rect.y:innerHeight*.42;for(let i=0;i<Math.min(count,low?10:28)&&layer.childElementCount<(low?16:48);i++){const n=document.createElement('span');n.className='bit-particle';n.dataset.effect=type;n.textContent=type==='xp'?'+XP':type==='crown'?'♛':type==='flame'?'◆':'✦';n.style.left=x+'px';n.style.top=y+'px';n.style.setProperty('--dx',(Math.random()-.5)*180+'px');n.style.setProperty('--dy',(-40-Math.random()*140)+'px');n.style.setProperty('--turn',(Math.random()-.5)*240+'deg');layer.append(n);setTimeout(()=>n.remove(),900);}}
let eyeFrame=0;document.addEventListener('pointermove',e=>{if(reduced()||document.hidden||eyeFrame)return;eyeFrame=requestAnimationFrame(()=>{eyeFrame=0;for(const n of document.querySelectorAll('.mascot-welcome .bit-stage')){const r=n.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)continue;const dx=Math.max(-3,Math.min(3,(e.clientX-r.x-r.width/2)/60)),dy=Math.max(-2,Math.min(2,(e.clientY-r.y-r.height/2)/80));n.querySelector('.bit-pupils').style.transform=`translate(${dx}px,${dy}px)`;}});},{passive:true});
function lab(){let d=document.getElementById('mascot-lab');if(!d){d=document.createElement('dialog');d.id='mascot-lab';d.innerHTML='<div class="game-dialog-head"><h2>Mascot Lab</h2><button data-overlay-close aria-label="Close">✕</button></div><div class="bit-mascot"></div><p>Local layered SVG · transform and opacity only · reduced-motion supported.</p><div class="mascot-controls">'+names.map(n=>`<button data-bit="${n}">${n}</button>`).join('')+'</div><div class="mascot-controls">'+['confetti','xp','flame','crown','sparkle'].map(n=>`<button data-vfx="${n}">${n}</button>`).join('')+'</div>';document.body.append(d);d.addEventListener('click',e=>{if(e.target.dataset.bit)play(e.target.dataset.bit);if(e.target.dataset.vfx)burst(20,e.target.dataset.vfx);});}mount();CBOverlays.open(d);}
window.bit=window.CBMascot={play,speak,lab,states:names,get state(){return state;},svg};window.CBFeedback={sound,burst,mood:(next,duration)=>play(next==='thinking'?'think':next,{duration})};
window.addEventListener('cb:thinking',()=>play('think',{duration:10000}));let lastBuild=null;window.addEventListener('cb:build',e=>{if(lastBuild===e.detail.runId)return;lastBuild=e.detail.runId;sound('build-success');burst(12);play('cheer');});window.addEventListener('cb:run-done',()=>play('idle'));window.addEventListener('cb:code-error',()=>{play('oops');speak(phrases.oops);sound('syntax-error');});window.addEventListener('cb:lesson-error',()=>{play('encouraging');speak(phrases.encouraging);sound('syntax-error');});
const seen=new Set();window.addEventListener('cb:mission',e=>{if(seen.has(e.detail.runId))return;seen.add(e.detail.runId);if(seen.size>100)seen.delete(seen.values().next().value);play('celebrate');speak(phrases.celebrate);if(e.detail.first){sound('build-success');burst(20,'xp');}});window.addEventListener('cb:reward',()=>{sound('coins-claimed');burst(16,'crown');play('level-up');});window.addEventListener('cb:economy',()=>{for(const n of document.querySelectorAll('.mascot-welcome .bit-stage'))skin(n);});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',apply);window.addEventListener('cb:settings',apply);document.addEventListener('visibilitychange',()=>{if(document.hidden){layer.replaceChildren();clearTimeout(timer);state='idle';}apply();});
const button=document.createElement('button');button.textContent='Mascot Lab';button.onclick=lab;document.getElementById('menu').append(button);
})();
