'use strict';
(()=>{
const dialog=document.createElement('dialog');dialog.id='cosmetic-store';dialog.setAttribute('aria-label','Cosmetic store');document.body.append(dialog);
function apply(){const p=CodeBridgeAcademy.getProgress(),e=p.economy;if(!e)return;for(const [slot,key]of [['editorPalette','cosmeticPalette'],['uiBorder','cosmeticBorder']])document.documentElement.dataset[key]=CBEconomy.catalog.find(i=>i.id===e.equipped[slot])?.assetKey||'default';}
function render(){const p=CodeBridgeAcademy.getProgress(),e=p.economy;dialog.innerHTML='<div class="game-dialog-head"><h2>Make it yours</h2><button id="store-close" aria-label="Close store">✕</button></div><p>✦ '+p.coins+' coins · cosmetics only, every coding tool stays free.</p><div class="store-grid">'+CBEconomy.catalog.map(item=>{const owned=e.ownedItemIds.includes(item.id),equipped=e.equipped[CBEconomy.slots[item.category]]===item.id;let preview=item.category==='bit_skin'?`<div class="store-sprite" data-skin="${item.assetKey}"></div>`:`<pre class="store-preview ${item.assetKey}">int main() {<br>  return 42;<br>}</pre>`;return `<article class="store-card">${preview}<h3>${item.name}</h3><small>${item.category.replaceAll('_',' ')} · ${item.priceCoins?item.priceCoins+' coins':'Included'}</small><button data-store="${item.id}" ${equipped||!owned&&p.coins<item.priceCoins?'disabled':''}>${equipped?'Equipped':owned?'Equip':'Unlock · '+item.priceCoins}</button></article>`;}).join('')+'</div><button id="economy-export">Export economy JSON</button><p class="small">Purchases save on this device. Export progress from Profile to back up ownership. Preview colours above before unlocking.</p>';
dialog.querySelector('#store-close').onclick=()=>dialog.close();dialog.querySelector('#economy-export').onclick=()=>{const json=JSON.stringify(CBEconomy.snapshot(CodeBridgeAcademy.getProgress()),null,2);if(window.AndroidFiles)AndroidFiles.save('CodeBridge-economy.json',json);else browserDownload('CodeBridge-economy.json',json);};dialog.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>{const id=b.dataset.store,owned=CodeBridgeAcademy.getProgress().economy.ownedItemIds.includes(id);if(CodeBridgeAcademy.transact(p=>owned?CBEconomy.equip(p,id):CBEconomy.buy(p,id))){render();apply();}});}
function mount(){const host=document.querySelector('.profile-actions');if(host&&!document.getElementById('store-open')){const button=document.createElement('button');button.id='store-open';button.textContent='Cosmetic store →';button.onclick=()=>{render();dialog.showModal();};host.prepend(button);}}
new MutationObserver(mount).observe(document.getElementById('academy'),{childList:true,subtree:true});mount();apply();window.addEventListener('cb:economy',apply);window.addEventListener('cb:settings',apply);
})();
