plugins { id 'com.android.application' }

android {
    namespace 'com.codebridge.mobile'
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'
    compileSdk 35
    defaultConfig {
        applicationId 'com.codebridge.mobile'
        minSdk 26
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
        targetSdk 35
        versionCode 7
        versionName '0.7.0'
    }
    androidResources { noCompress += ['wasm', 'tar', 'whl', 'zip'] }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
